# -- Labels based on PR title ------------------------------------------------
'fix':
  - head-branch: ['fix']

'enhancement':
  - head-branch: ['feat']

# -- Documentation label ----------------------------------------------------
'docs':
- changed-files:
  - any-glob-to-any-file: ['doc/source/**/*', 'README.md']

## -- Other labels ------------------------------------------------------------
'ci':
- changed-files:
  - any-glob-to-any-file: ['.github/workflows/**']

'maintenance':
- changed-files:
  - any-glob-to-any-file: ['.github/**/*', '.flake8', 'pyproject.toml', 'tox.ini', '.pre-commit-config.yaml']

'tests':
- changed-files:
  - any-glob-to-any-file: ['tests/**']

# HACK: the following labels are declared with the only purpose of avoiding the
# GitHub labeler bot to remove those. This is a known issue reported in the
# official action/labeler repo https://github.com/actions/labeler/issues/763
'ci:skip':
- changed-files:
  - all-globs-to-all-files: ['THIS-NEVER-MATCHES-A-FILE']

'docs:skip':
- changed-files:
  - all-globs-to-all-files: ['THIS-NEVER-MATCHES-A-FILE']

'tests:skip':
- changed-files:
  - all-globs-to-all-files: ['THIS-NEVER-MATCHES-A-FILE']