# Copyright (C) 2023 - 2025 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

from ansys.rocky.core._api_stubs.rocky30.plugins.api.conveyors.ra_base_conveyor import (
    RABaseConveyor as RABaseConveyor,
)
from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_addins import (
    ElementWithAddins as ElementWithAddins,
)

class RAFeedConveyor(RABaseConveyor, ElementWithAddins):
    @classmethod
    def GetWrappedClass(cls): ...
    @classmethod
    def GetClassName(cls): ...
    def GetAccelerationPeriod(self, unit: str | None = None) -> float: ...
    def SetAccelerationPeriod(
        self, value: str | float, unit: str | None = None
    ) -> None: ...
    def GetBeginningStopTime(self, unit: str | None = None) -> float: ...
    def SetBeginningStopTime(
        self, value: str | float, unit: str | None = None
    ) -> None: ...
    def GetBeltSpeed(self, unit: str | None = None) -> float: ...
    def SetBeltSpeed(self, value: str | float, unit: str | None = None) -> None: ...
    def GetDecelerationPeriod(self, unit: str | None = None) -> float: ...
    def SetDecelerationPeriod(
        self, value: str | float, unit: str | None = None
    ) -> None: ...
    def GetBeginningStartTime(self, unit: str | None = None) -> float: ...
    def SetBeginningStartTime(
        self, value: str | float, unit: str | None = None
    ) -> None: ...
    def GetCapillaryFrictionCoefficient(self) -> float: ...
    def SetCapillaryFrictionCoefficient(self, value: str | float) -> None: ...
    def GetDropBoxHeight(self, unit: str | None = None) -> float: ...
    def SetDropBoxHeight(self, value: str | float, unit: str | None = None) -> None: ...
    def GetDropBoxLength(self, unit: str | None = None) -> float: ...
    def SetDropBoxLength(self, value: str | float, unit: str | None = None) -> None: ...
    def GetDropBoxWidth(self, unit: str | None = None) -> float: ...
    def SetDropBoxWidth(self, value: str | float, unit: str | None = None) -> None: ...
    def GetFrontPlateOffset(self, unit: str | None = None) -> float: ...
    def SetFrontPlateOffset(
        self, value: str | float, unit: str | None = None
    ) -> None: ...
    def GetWallThickness(self, unit: str | None = None) -> float: ...
    def SetWallThickness(self, value: str | float, unit: str | None = None) -> None: ...
    def GetBeltThickness(self, unit: str | None = None) -> float: ...
    def SetBeltThickness(self, value: str | float, unit: str | None = None) -> None: ...
    def GetBeltWidth(self, unit: str | None = None) -> float: ...
    def SetBeltWidth(self, value: str | float, unit: str | None = None) -> None: ...
    def GetLoadingLength(self, unit: str | None = None) -> float: ...
    def SetLoadingLength(self, value: str | float, unit: str | None = None) -> None: ...
    def GetTemperature(self, unit: str | None = None) -> float: ...
    def SetTemperature(self, value: str | float, unit: str | None = None) -> None: ...
    def GetThermalBoundaryConditionType(self) -> str: ...
    def SetThermalBoundaryConditionType(self, value: str) -> None: ...
    def GetValidThermalBoundaryConditionTypeValues(self) -> list[str]: ...
    def GetTransitionLength(self, unit: str | None = None) -> float: ...
    def SetTransitionLength(
        self, value: str | float, unit: str | None = None
    ) -> None: ...
    def GetTriangleSize(self, unit: str | None = None) -> float: ...
    def SetTriangleSize(self, value: str | float, unit: str | None = None) -> None: ...
    def GetDiameter(self, unit: str | None = None) -> float: ...
    def SetDiameter(self, value: str | float, unit: str | None = None) -> None: ...
    def GetFaceWidth(self, unit: str | None = None) -> float: ...
    def SetFaceWidth(self, value: str | float, unit: str | None = None) -> None: ...
    def GetOffsetToIdlers(self, unit: str | None = None) -> float: ...
    def SetOffsetToIdlers(self, value: str | float, unit: str | None = None) -> None: ...
    def GetName(self) -> str: ...
    def SetName(self, value: str) -> None: ...
    def GetAlignmentAngle(self, unit: str | None = None) -> float: ...
    def SetAlignmentAngle(self, value: str | float, unit: str | None = None) -> None: ...
    def GetBeltInclineAngle(self, unit: str | None = None) -> float: ...
    def SetBeltInclineAngle(
        self, value: str | float, unit: str | None = None
    ) -> None: ...
    def GetHorizontalOffset(self, unit: str | None = None) -> float: ...
    def SetHorizontalOffset(
        self, value: str | float, unit: str | None = None
    ) -> None: ...
    def GetOutOfPlaneOffset(self, unit: str | None = None) -> float: ...
    def SetOutOfPlaneOffset(
        self, value: str | float, unit: str | None = None
    ) -> None: ...
    def GetReturnBeltAngle(self, unit: str | None = None) -> float: ...
    def SetReturnBeltAngle(self, value: str | float, unit: str | None = None) -> None: ...
    def GetVerticalOffset(self, unit: str | None = None) -> float: ...
    def SetVerticalOffset(self, value: str | float, unit: str | None = None) -> None: ...
    def GetSkirtboardHeight(self, unit: str | None = None) -> float: ...
    def SetSkirtboardHeight(
        self, value: str | float, unit: str | None = None
    ) -> None: ...
    def GetHeightOffset(self, unit: str | None = None) -> float: ...
    def SetHeightOffset(self, value: str | float, unit: str | None = None) -> None: ...
    def GetSkirtboardLength(self, unit: str | None = None) -> float: ...
    def SetSkirtboardLength(
        self, value: str | float, unit: str | None = None
    ) -> None: ...
    def GetLengthOffset(self, unit: str | None = None) -> float: ...
    def SetLengthOffset(self, value: str | float, unit: str | None = None) -> None: ...
    def GetWidth(self, unit: str | None = None) -> float: ...
    def SetWidth(self, value: str | float, unit: str | None = None) -> None: ...
    def GetSphBoundaryType(self) -> str: ...
    def SetSphBoundaryType(self, value: str) -> None: ...
    def GetValidSphBoundaryTypeValues(self) -> list[str]: ...
    def GetSurfaceTensionContactAngle(self, unit: str | None = None) -> float: ...
    def SetSurfaceTensionContactAngle(
        self, value: str | float, unit: str | None = None
    ) -> None: ...
    def GetMaterial(self): ...
    def SetMaterial(self, value) -> None: ...
    def GetAvailableMaterials(self): ...
