from ansys.rocky.core._api_stubs.plugins10.plugins.api.api_element_item import ApiElementItem
from typing import Optional, Union

class RAFiveRollsBeltProfile(ApiElementItem):
    @classmethod
    def GetWrappedClass(cls): ...
    @classmethod
    def GetClassName(cls): ...
    def GetCenterRollLength(self, unit: Optional[str] = ...) -> float: ...
    def SetCenterRollLength(self, value: Union[str, float], unit: Optional[str] = ...) -> None: ...
    def GetLastRollAngle(self, unit: Optional[str] = ...) -> float: ...
    def SetLastRollAngle(self, value: Union[str, float], unit: Optional[str] = ...) -> None: ...
    def GetLowerCornerRadius(self, unit: Optional[str] = ...) -> float: ...
    def SetLowerCornerRadius(self, value: Union[str, float], unit: Optional[str] = ...) -> None: ...
    def GetSideRollLength(self, unit: Optional[str] = ...) -> float: ...
    def SetSideRollLength(self, value: Union[str, float], unit: Optional[str] = ...) -> None: ...
    def GetTroughingAngle(self, unit: Optional[str] = ...) -> float: ...
    def SetTroughingAngle(self, value: Union[str, float], unit: Optional[str] = ...) -> None: ...
    def GetUpperCornerRadius(self, unit: Optional[str] = ...) -> float: ...
    def SetUpperCornerRadius(self, value: Union[str, float], unit: Optional[str] = ...) -> None: ...
    def GetUse0223RatioForRollLengths(self) -> bool: ...
    def SetUse0223RatioForRollLengths(self, value: bool) -> None: ...
    def EnableUse0223RatioForRollLengths(self) -> None: ...
    def DisableUse0223RatioForRollLengths(self) -> None: ...
    def IsUse0223RatioForRollLengthsEnabled(self) -> bool: ...
    def GetMaterial(self): ...
    def SetMaterial(self, value) -> None: ...
    def GetAvailableMaterials(self): ...
