# Copyright (C) 2023 - 2025 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

from ansys.rocky.core._api_stubs.plugins10.plugins.api.api_element_item import (
    ApiElementItem,
)

class RAFiveRollsBeltProfile(ApiElementItem):
    @classmethod
    def GetWrappedClass(cls): ...
    @classmethod
    def GetClassName(cls): ...
    def GetCenterRollLength(self, unit: str | None = None) -> float: ...
    def SetCenterRollLength(
        self, value: str | float, unit: str | None = None
    ) -> None: ...
    def GetLastRollAngle(self, unit: str | None = None) -> float: ...
    def SetLastRollAngle(self, value: str | float, unit: str | None = None) -> None: ...
    def GetLowerCornerRadius(self, unit: str | None = None) -> float: ...
    def SetLowerCornerRadius(
        self, value: str | float, unit: str | None = None
    ) -> None: ...
    def GetSideRollLength(self, unit: str | None = None) -> float: ...
    def SetSideRollLength(self, value: str | float, unit: str | None = None) -> None: ...
    def GetTroughingAngle(self, unit: str | None = None) -> float: ...
    def SetTroughingAngle(self, value: str | float, unit: str | None = None) -> None: ...
    def GetUpperCornerRadius(self, unit: str | None = None) -> float: ...
    def SetUpperCornerRadius(
        self, value: str | float, unit: str | None = None
    ) -> None: ...
    def GetUse0223RatioForRollLengths(self) -> bool: ...
    def SetUse0223RatioForRollLengths(self, value: bool) -> None: ...
    def EnableUse0223RatioForRollLengths(self) -> None: ...
    def DisableUse0223RatioForRollLengths(self) -> None: ...
    def IsUse0223RatioForRollLengthsEnabled(self) -> bool: ...
    def GetMaterial(self): ...
    def SetMaterial(self, value) -> None: ...
    def GetAvailableMaterials(self): ...
