from ansys.rocky.core._api_stubs.plugins10.plugins.api.api_element_item import ApiElementItem

class RAOneRollBeltProfile(ApiElementItem):
    @classmethod
    def GetWrappedClass(cls): ...
    @classmethod
    def GetClassName(cls): ...
    def GetMaterial(self): ...
    def SetMaterial(self, value) -> None: ...
    def GetAvailableMaterials(self): ...
