from ansys.rocky.core._api_stubs.plugins10.plugins.api.api_element_item import ApiElementItem
from typing import Optional, Union

class RAThreeRollsBeltProfile(ApiElementItem):
    @classmethod
    def GetWrappedClass(cls): ...
    @classmethod
    def GetClassName(cls): ...
    def GetCenterRollLength(self, unit: Optional[str] = ...) -> float: ...
    def SetCenterRollLength(self, value: Union[str, float], unit: Optional[str] = ...) -> None: ...
    def GetLowerCornerRadius(self, unit: Optional[str] = ...) -> float: ...
    def SetLowerCornerRadius(self, value: Union[str, float], unit: Optional[str] = ...) -> None: ...
    def GetTroughingAngle(self, unit: Optional[str] = ...) -> float: ...
    def SetTroughingAngle(self, value: Union[str, float], unit: Optional[str] = ...) -> None: ...
    def GetUse0371RatioForRollLengths(self) -> bool: ...
    def SetUse0371RatioForRollLengths(self, value: bool) -> None: ...
    def EnableUse0371RatioForRollLengths(self) -> None: ...
    def DisableUse0371RatioForRollLengths(self) -> None: ...
    def IsUse0371RatioForRollLengthsEnabled(self) -> bool: ...
    def GetMaterial(self): ...
    def SetMaterial(self, value) -> None: ...
    def GetAvailableMaterials(self): ...
