from ansys.rocky.core._api_stubs.plugins10.plugins.api.api_element_item import ApiElementItem
from typing import Optional, Union

class RATwoRollsBeltProfile(ApiElementItem):
    @classmethod
    def GetWrappedClass(cls): ...
    @classmethod
    def GetClassName(cls): ...
    def GetLowerCornerRadius(self, unit: Optional[str] = ...) -> float: ...
    def SetLowerCornerRadius(self, value: Union[str, float], unit: Optional[str] = ...) -> None: ...
    def GetTroughingAngle(self, unit: Optional[str] = ...) -> float: ...
    def SetTroughingAngle(self, value: Union[str, float], unit: Optional[str] = ...) -> None: ...
    def GetMaterial(self): ...
    def SetMaterial(self, value) -> None: ...
    def GetAvailableMaterials(self): ...
