from rocky30.base_types import Tuple3F as Tuple3F
from rocky30.core.geometry.rocky_document_constants import UNIT_PLANE_ANGLE as UNIT_PLANE_ANGLE

class _RAOrientationMixin:
    def GetOrientation(self, unit: str = ...) -> Tuple3F: ...
    def SetOrientation(self, rotation: Tuple3F, unit: str = ...) -> None: ...
    def SetOrientationFromAngles(self, rotation: Tuple3F, unit: str = ..., local_angles: bool = ..., order: str = ...) -> None: ...
    def SetOrientationFromAngleAndVector(self, angle: float, vector: Tuple3F, unit: str = ...) -> None: ...
    def SetOrientationFromBasisVector(self, vector_x: Tuple3F, vector_y: Tuple3F, vector_z: Tuple3F) -> None: ...
    def GetOrientationFromAngles(self, unit: str = ...) -> Tuple3F: ...
    def GetOrientationFromAngleAndVector(self, unit: str = ...) -> tuple[float, Tuple3F]: ...
    def GetOrientationFromBasisVector(self) -> tuple[Tuple3F, Tuple3F, Tuple3F]: ...
