from ansys.rocky.core._api_stubs.plugins10.plugins.api.api_element_item import ApiError

class RockyApiError(ApiError): ...

def CheckResults(ra_object) -> None: ...
def CheckPropAffectsSimulation(prop_owner, prop_name): ...
