from collections.abc import Iterable
from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_project import RAProject as RAProject
from ansys.rocky.core._api_stubs.rocky30.plugins.api.rocky_api_deprecated_decorator import ApiDeprecated as ApiDeprecated
from rocky30.plugins.preferences.additional_features import AdditionalFeature as AdditionalFeature, GetAdditionalFeatureValue as GetAdditionalFeatureValue, SetAdditionalFeatureValue as SetAdditionalFeatureValue

class RAAdditionalFeatures:
    def GetBetaFeaturesEnabled(self) -> bool: ...
    def SetBetaFeaturesEnabled(self, enable: bool) -> None: ...
    def GetAdvancedFeaturesEnabled(self) -> bool: ...
    def SetAdvancedFeaturesEnabled(self, enable: bool) -> None: ...
    def GetCustomFeatures(self) -> list[str]: ...
    def SetCustomFeatures(self, features: Iterable[str]) -> None: ...
    def GetMeshedParticlesUpscalingEnabled(self) -> bool: ...
    def SetMeshedParticlesUpscalingEnabled(self, enable: bool) -> None: ...
