from ansys.rocky.core._api_stubs.plugins10.plugins.api.api_element_item import ApiElementItem

class RABaseTagging(ApiElementItem):
    def GetTimeRangeFilter(self): ...
    def GetGridFunctionName(self): ...
