from ansys.rocky.core._api_stubs.plugins10.plugins.api.api_element_item import ApiElementItem
from ansys.rocky.core._api_stubs.rocky30.plugins.api.motion.ra_motion_frame import RAMotionFrame as RAMotionFrame
from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_addins import ElementWithAddins as ElementWithAddins
from typing import Optional, Union

class RACustomInput(ApiElementItem, ElementWithAddins):
    @classmethod
    def GetWrappedClass(self): ...
    @classmethod
    def GetClassName(self): ...
    def GetFilePath(self): ...
    def SetFilePath(self, file_path) -> None: ...
    def GetMotionFrame(self): ...
    def SetMotionFrame(self, motion_frame: Union['RAMotionFrame', str, None]) -> None: ...
    def GetAvailableMotionFrames(self): ...
    def GetDefaultTemperature(self, unit: Optional[str] = ...) -> float: ...
    def SetDefaultTemperature(self, value: Union[str, float], unit: Optional[str] = ...) -> None: ...
    def GetName(self) -> str: ...
    def SetName(self, value: str) -> None: ...
    def GetParticle(self): ...
    def SetParticle(self, value) -> None: ...
    def GetAvailableParticles(self): ...
