from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_grid_process_element import RAGridProcessElementItem as RAGridProcessElementItem
from ansys.rocky.core._api_stubs.rocky30.plugins.api.rocky_api_deprecated_decorator import ApiDeprecated as ApiDeprecated

class RAContactData(RAGridProcessElementItem):
    @classmethod
    def GetWrappedClass(self): ...
    @classmethod
    def GetClassName(self): ...
    def RemoveProcess(self) -> None: ...
    def GetCollectContactsData(self) -> bool: ...
    def SetCollectContactsData(self, value: bool) -> None: ...
    def EnableCollectContactsData(self) -> None: ...
    def DisableCollectContactsData(self) -> None: ...
    def IsCollectContactsDataEnabled(self) -> bool: ...
    def GetIncludeAdhesiveContacts(self) -> bool: ...
    def SetIncludeAdhesiveContacts(self, value: bool) -> None: ...
    def EnableIncludeAdhesiveContacts(self) -> None: ...
    def DisableIncludeAdhesiveContacts(self) -> None: ...
    def IsIncludeAdhesiveContactsEnabled(self) -> bool: ...
