from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_base_tagging import RABaseTagging as RABaseTagging
from typing import Union

class RADivisionsTagging(RABaseTagging):
    @classmethod
    def GetWrappedClass(self): ...
    @classmethod
    def GetClassName(self): ...
    def GetDivisionsI(self) -> int: ...
    def SetDivisionsI(self, value: Union[str, int]) -> None: ...
    def GetDivisionsJ(self) -> int: ...
    def SetDivisionsJ(self, value: Union[str, int]) -> None: ...
    def GetDivisionsK(self) -> int: ...
    def SetDivisionsK(self, value: Union[str, int]) -> None: ...
    def GetNameMask(self) -> str: ...
    def SetNameMask(self, value: str) -> None: ...
    def GetTagStride(self) -> int: ...
    def SetTagStride(self, value: Union[str, int]) -> None: ...
    def GetTagValue(self) -> int: ...
    def SetTagValue(self, value: Union[str, int]) -> None: ...
