# Copyright (C) 2023 - 2025 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

from collections.abc import Sequence

from ansys.rocky.core._api_stubs.plugins10.plugins.api.api_element_item import (
    ApiElementItem,
)

class RADomainSettings(ApiElementItem):
    @classmethod
    def GetWrappedClass(self): ...
    @classmethod
    def GetClassName(self) -> str: ...
    def CoordinateLimitsAtBoundaryLimits(self) -> bool: ...
    def GetCoordinateLimitsMinMax(self): ...
    def ResetDomainToGeometriesLimits(self) -> None: ...
    def GetCoordinateLimitsMaxValues(self, unit: str | None = None) -> list[float]: ...
    def SetCoordinateLimitsMaxValues(
        self, values: Sequence[str | float], unit: str | None = None
    ) -> None: ...
    def GetCoordinateLimitsMinValues(self, unit: str | None = None) -> list[float]: ...
    def SetCoordinateLimitsMinValues(
        self, values: Sequence[str | float], unit: str | None = None
    ) -> None: ...
    def GetUseBoundaryLimits(self) -> bool: ...
    def SetUseBoundaryLimits(self, value: bool) -> None: ...
    def EnableUseBoundaryLimits(self) -> None: ...
    def DisableUseBoundaryLimits(self) -> None: ...
    def IsUseBoundaryLimitsEnabled(self) -> bool: ...
    def GetPeriodicLimitsMaxCoordinates(self, unit: str | None = None) -> list[float]: ...
    def SetPeriodicLimitsMaxCoordinates(
        self, values: Sequence[str | float], unit: str | None = None
    ) -> None: ...
    def GetPeriodicLimitsMinCoordinates(self, unit: str | None = None) -> list[float]: ...
    def SetPeriodicLimitsMinCoordinates(
        self, values: Sequence[str | float], unit: str | None = None
    ) -> None: ...
    def GetPeriodicAtGeometryLimits(self) -> bool: ...
    def SetPeriodicAtGeometryLimits(self, value: bool) -> None: ...
    def EnablePeriodicAtGeometryLimits(self) -> None: ...
    def DisablePeriodicAtGeometryLimits(self) -> None: ...
    def IsPeriodicAtGeometryLimitsEnabled(self) -> bool: ...
    def GetCartesianPeriodicDirections(self) -> str: ...
    def SetCartesianPeriodicDirections(self, value: str) -> None: ...
    def GetValidCartesianPeriodicDirectionsValues(self) -> list[str]: ...
    def GetInitialAngle(self, unit: str | None = None) -> float: ...
    def SetInitialAngle(self, value: str | float, unit: str | None = None) -> None: ...
    def GetNumberOfDivisions(self) -> int: ...
    def SetNumberOfDivisions(self, value: str | int) -> None: ...
    def GetCylindricalPeriodicDirections(self) -> str: ...
    def SetCylindricalPeriodicDirections(self, value: str) -> None: ...
    def GetValidCylindricalPeriodicDirectionsValues(self) -> list[str]: ...
    def GetDomainType(self) -> str: ...
    def SetDomainType(self, value: str) -> None: ...
    def GetValidDomainTypeValues(self) -> list[str]: ...
