from _typeshed import Incomplete
from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_process_element import RAUserProcess as RAUserProcess

class RAEulerianStatistics(RAUserProcess):
    @classmethod
    def GetWrappedClass(self): ...
    @classmethod
    def GetClassName(self): ...
    def GetDivisions(self): ...
    def SetDivisions(self, divisions) -> None: ...
    def GetParticleGridFunctionNames(self): ...
    def GetAvailableOperations(self): ...
    def CreateEulerianGridFunction(self, operation_name, value_name, weight_name: Incomplete | None = ...): ...
