# Copyright (C) 2023 - 2025 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

from rocky30.models.input.sph_inlet import SPHInlet as SPHInlet

from ansys.rocky.core._api_stubs.plugins10.plugins.api.api_element_item import (
    ApiElementItem,
)

class RAFluidInlet(ApiElementItem):
    @classmethod
    def GetWrappedClass(self) -> type[SPHInlet]: ...
    @classmethod
    def GetClassName(self) -> str: ...
    def GetBoundaryCondition(self) -> str: ...
    def SetBoundaryCondition(self, value: str) -> None: ...
    def GetValidBoundaryConditionValues(self) -> list[str]: ...
    def GetMassFlowRate(self, unit: str | None = None) -> float: ...
    def SetMassFlowRate(self, value: str | float, unit: str | None = None) -> None: ...
    def GetName(self) -> str: ...
    def SetName(self, value: str) -> None: ...
    def GetInjectionDuration(self, unit: str | None = None) -> float: ...
    def SetInjectionDuration(
        self, value: str | float, unit: str | None = None
    ) -> None: ...
    def GetPeriodic(self) -> bool: ...
    def SetPeriodic(self, value: bool) -> None: ...
    def EnablePeriodic(self) -> None: ...
    def DisablePeriodic(self) -> None: ...
    def IsPeriodicEnabled(self) -> bool: ...
    def GetPeriod(self, unit: str | None = None) -> float: ...
    def SetPeriod(self, value: str | float, unit: str | None = None) -> None: ...
    def GetStartTime(self, unit: str | None = None) -> float: ...
    def SetStartTime(self, value: str | float, unit: str | None = None) -> None: ...
    def GetStopTime(self, unit: str | None = None) -> float: ...
    def SetStopTime(self, value: str | float, unit: str | None = None) -> None: ...
    def GetTemperature(self, unit: str | None = None) -> float: ...
    def SetTemperature(self, value: str | float, unit: str | None = None) -> None: ...
    def GetVelocity(self, unit: str | None = None) -> float: ...
    def SetVelocity(self, value: str | float, unit: str | None = None) -> None: ...
    def GetEntryPoint(self): ...
    def SetEntryPoint(self, value) -> None: ...
    def GetAvailableEntryPoints(self): ...
