from barril.units import FixedArray as FixedArray
from coilib50.subject import Subject as Subject
from coilib50.time.time_step_interface import ITimeStep as ITimeStep
from collections.abc import Iterator
from ansys.rocky.core._api_stubs.plugins10.plugins.api.api_element_item import ApiElementItem
from rocky30.models.geometry.geometry_collection import GeometryCollection as GeometryCollection
from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_api import CheckResults as CheckResults, RockyApiError as RockyApiError
from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_base_geometry import RABaseGeometry as RABaseGeometry
from ansys.rocky.core._api_stubs.rocky30.plugins.api.rocky_api_deprecated_decorator import ApiDeprecated as ApiDeprecated

class RAGeometryCollection(ApiElementItem):
    @classmethod
    def GetWrappedClass(cls) -> type[GeometryCollection]: ...
    @classmethod
    def GetClassName(cls) -> str: ...
    def GetGeometryNames(self) -> list[str]: ...
    def GetGeometry(self, geometry_name): ...
    def IterInputGeometries(self) -> Iterator[RABaseGeometry]: ...
    def IterInletGeometries(self) -> Iterator[RABaseGeometry]: ...
    def IterSurfaces(self) -> Iterator[RABaseGeometry]: ...
    def IterWalls(self) -> Iterator[RABaseGeometry]: ...
    def IterSystemCouplingWalls(self) -> Iterator[RABaseGeometry]: ...
    def GetBoundingBox(self, time_step: Union[ITimeStep, None], force_load: bool = ...) -> tuple[FixedArray, FixedArray]: ...
    def RemoveGeometry(self, geometry: Union[RABaseGeometry, str, None]) -> None: ...
    def __iter__(self) -> Iterator[ApiElementItem]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> RABaseGeometry: ...
