from ansys.rocky.core._api_stubs.plugins10.plugins.api.api_element_item import ApiElementItem
from typing import Union

class RAInputVariables(ApiElementItem):
    @classmethod
    def GetWrappedClass(cls): ...
    @classmethod
    def GetClassName(cls) -> str: ...
    def CreateVariable(self, name: str, value: float = ...) -> RAParametricVar: ...
    def RemoveVariable(self, variable: Union['RAParametricVar', str]) -> None: ...
    def GetVariableByName(self, name: str) -> RAParametricVar: ...
    def __len__(self): ...
    def __getitem__(self, index): ...
    def __iter__(self): ...

class RAParametricVar(ApiElementItem):
    @classmethod
    def GetWrappedClass(cls): ...
    @classmethod
    def GetClassName(cls) -> str: ...
    def GetName(self) -> str: ...
    def GetValue(self) -> float: ...
    def SetValue(self, value: float) -> None: ...
