# Copyright (C) 2023 - 2025 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

from collections.abc import Sequence

from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_base_geometry import (
    RABaseGeometry as RABaseGeometry,
)
from ansys.rocky.core._api_stubs.rocky30.plugins.api.rocky_api_utils import (
    ConvertUserPassedValueToScalar as ConvertUserPassedValueToScalar,
)

class RAInletGeometry(RABaseGeometry):
    @classmethod
    def GetWrappedClass(self): ...
    def SetGeometryType(self, geometry_type: str) -> None: ...
    def GetGeometryType(self) -> str: ...
    def GetRectangularSize(self, unit: str | None = None) -> tuple[float, float]: ...
    def SetRectangularSize(
        self, length: float, width: float, unit: str | None = None
    ) -> None: ...
    @classmethod
    def GetClassName(self) -> str: ...
    def GetCircularMinMaxRadius(self, unit: str | None = None) -> tuple[float, float]: ...
    def SetCircularMinMaxRadius(
        self, min_radius: float, max_radius: float, unit: str | None = None
    ) -> None: ...
    def GetAlignmentAngle(self, unit: str | None = None) -> float: ...
    def SetAlignmentAngle(self, value: str | float, unit: str | None = None) -> None: ...
    def GetCenter(self, unit: str | None = None) -> list[float]: ...
    def SetCenter(
        self, values: Sequence[str | float], unit: str | None = None
    ) -> None: ...
    def GetLength(self, unit: str | None = None) -> float: ...
    def SetLength(self, value: str | float, unit: str | None = None) -> None: ...
    def GetWidth(self, unit: str | None = None) -> float: ...
    def SetWidth(self, value: str | float, unit: str | None = None) -> None: ...
    def GetInclineAngle(self, unit: str | None = None) -> float: ...
    def SetInclineAngle(self, value: str | float, unit: str | None = None) -> None: ...
    def GetName(self) -> str: ...
    def SetName(self, value: str) -> None: ...
