from _typeshed import Incomplete
from coilib50.subject import Subject
from esss_qt10 import qt_traits
from kraken20.plugins.api.ka_workspace_window import KAWorkspaceWindow
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from mpl_toolkits.mplot3d import Axes3D as Axes3D
from plugins10.plugins.mainwindow.mainwindowplugins.centralwidget import DefaultCentralEditor
from plugins10.plugins.workspace.workspace_editor_subjects.workspace_editor_subjects import WorkspaceEditorSubject

class MplCanvas(FigureCanvas):
    figure: Incomplete
    def __init__(self) -> None: ...

class MplWindow(qt_traits.QWidget, DefaultCentralEditor):
    frame: Incomplete
    canvas: Incomplete
    mpltoolbar: Incomplete
    vbl: Incomplete
    def __init__(self, parent, central_editor_id) -> None: ...
    def GetFigure(self): ...

class MplWindowSubject(WorkspaceEditorSubject):
    def GetGUIClass(self): ...
    def GetIgnoreChanges(self): ...
    def GetIgnoreAddRemove(self): ...
    def GetIgnoreAdd(self): ...

class RAMplWindow(KAWorkspaceWindow):
    def GetFigure(self): ...
    def GetCanvas(self): ...
    def Redraw(self): ...

class UserWindowSubjectContainer(Subject):
    app: Incomplete
    def __init__(self, app) -> None: ...
    def GetIgnoreChanges(self): ...
    def GetIgnoreAddRemove(self): ...
    def GetIgnoreAdd(self): ...
    def Add(self, window_subject): ...
    def __iter__(self): ...
