from ansys.rocky.core._api_stubs.plugins10.plugins.api.api_element_item import ApiElementItem
from rocky30.models.material.fluid_material import FluidMaterial as FluidMaterial, FluidMaterialCollection as FluidMaterialCollection
from rocky30.models.material.material import Material as Material, MaterialCollection as MaterialCollection
from rocky30.models.naming import CreateNewName as CreateNewName
from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_fluid_material import RAFluidMaterial as RAFluidMaterial
from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_list import RAList as RAList
from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_materials_interaction_collection import RAMaterialsInteractionCollection as RAMaterialsInteractionCollection
from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_solid_material import RASolidMaterial as RASolidMaterial
from ansys.rocky.core._api_stubs.rocky30.plugins.api.rocky_api_deprecated_decorator import ApiDeprecated as ApiDeprecated
from typing import Union

class RAMaterialCollection(RAList):
    @classmethod
    def GetWrappedClass(cls) -> type['MaterialCollection']: ...
    @classmethod
    def GetClassName(cls) -> str: ...
    def __delitem__(self, index: int) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> ApiElementItem: ...
    def __getitem__(self, index: int) -> ApiElementItem: ...
    def Clear(self) -> None: ...
    def New(self) -> RASolidMaterial: ...
    def AddSolidMaterial(self) -> RASolidMaterial: ...
    def AddFluidMaterial(self) -> RAFluidMaterial: ...
    def GetDefaultMaterials(self) -> list['RASolidMaterial']: ...
    def GetDefaultSolidMaterials(self) -> list['RASolidMaterial']: ...
    def GetDefaultParticleMaterial(self) -> RASolidMaterial: ...
    def GetDefaultBeltMaterial(self) -> RASolidMaterial: ...
    def GetDefaultBoundaryMaterial(self) -> RASolidMaterial: ...
    def GetMaterial(self, material_name: str) -> RASolidMaterial: ...
    def GetSolidMaterial(self, material_name: str) -> RASolidMaterial: ...
    def GetDefaultFluidMaterial(self) -> RAFluidMaterial: ...
    def GetFluidMaterial(self, material_name: str) -> RAFluidMaterial: ...
    def GetMaterialsInteractionCollection(self) -> RAMaterialsInteractionCollection: ...
    def GetBulkSolidFraction(self) -> float: ...
    def SetBulkSolidFraction(self, value: Union[str, float]) -> None: ...
