from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_list import RAList as RAList
from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_materials_interaction import RAMaterialsInteraction as RAMaterialsInteraction

class RAMaterialsInteractionCollection(RAList[RAMaterialsInteraction]):
    @classmethod
    def GetWrappedClass(self): ...
    @classmethod
    def GetClassName(self): ...
    def New(self) -> None: ...
    def __delitem__(self, index) -> None: ...
    def Remove(self, item) -> None: ...
    def Clear(self) -> None: ...
    def GetMaterialsInteraction(self, material_1, material_2) -> RAMaterialsInteraction: ...
