from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_list import RAList as RAList
from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_particle import RAParticle as RAParticle

class RAParticleCollection(RAList[RAParticle]):
    @classmethod
    def GetWrappedClass(self): ...
    @classmethod
    def GetClassName(self) -> str: ...
    def GetParticleNames(self) -> list[str]: ...
    def GetParticle(self, particle_name: str) -> RAParticle: ...
    def New(self) -> RAParticle: ...
