from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_grid_process_element import RAGridProcessElementItem as RAGridProcessElementItem
from ansys.rocky.core._api_stubs.rocky30.plugins.api.rocky_api_deprecated_decorator import ApiDeprecated as ApiDeprecated

class RAParticleJointsData(RAGridProcessElementItem):
    @classmethod
    def GetWrappedClass(self): ...
    @classmethod
    def GetClassName(self): ...
    def RemoveProcess(self) -> None: ...
    def GetCollectJointData(self) -> bool: ...
    def SetCollectJointData(self, value: bool) -> None: ...
    def EnableCollectJointData(self) -> None: ...
    def DisableCollectJointData(self) -> None: ...
    def IsCollectJointDataEnabled(self) -> bool: ...
