# Copyright (C) 2023 - 2025 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

from collections.abc import Sequence

from _typeshed import Incomplete
from rocky30.models.particle.particle_geometry import (
    ParticleShapeTypes as ParticleShapeTypes,
)

from ansys.rocky.core._api_stubs.rocky30.plugins.api._ra_orientation_mixin import (
    _RAOrientationMixin,
)
from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_addins import (
    ElementWithAddins as ElementWithAddins,
)
from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_api import (
    RockyApiError as RockyApiError,
)
from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_grid_process_element import (
    RAGridProcessElementItem as RAGridProcessElementItem,
)
from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_particle_assembly import (
    RAParticleAssemblyCustom as RAParticleAssemblyCustom,
)
from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_particle_assembly import (
    RAParticleAssemblyPartList as RAParticleAssemblyPartList,
)
from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_size_distribution import (
    RASizeDistributionList as RASizeDistributionList,
)
from ansys.rocky.core._api_stubs.rocky30.plugins.api.rocky_api_deprecated_decorator import (
    ApiDeprecated as ApiDeprecated,
)

class RAParticle(RAGridProcessElementItem, ElementWithAddins, _RAOrientationMixin):
    @classmethod
    def GetWrappedClass(self): ...
    @classmethod
    def GetClassName(self) -> str: ...
    def ImportFromSTL(
        self, stl_filename: str, as_concave: bool, is_open: bool = False
    ) -> bool: ...
    def ImportCustomFiber(self, filename: str) -> bool: ...
    def GetSizeDistributionList(self) -> RASizeDistributionList: ...
    def GetUseMultipleElements(self) -> bool: ...
    def SetUseMultipleElements(self, value) -> None: ...
    def IsConcave(self): ...
    def GetBreakageModel(self) -> str: ...
    def GetValidBreakageModelValues(self) -> list[str]: ...
    def SetBreakageModel(self, value: str) -> None: ...
    def GetAssemblyParts(self) -> RAParticleAssemblyPartList: ...
    def GetAssemblyCustom(self) -> RAParticleAssemblyCustom: ...
    def GetCustomProperties(self) -> RAParticleAssemblyCustom: ...
    def GetAbt10MaximumT10Value(self, unit: str | None = None) -> float: ...
    def SetAbt10MaximumT10Value(
        self, value: str | float, unit: str | None = None
    ) -> None: ...
    def GetAbt10ReferenceMinimumSpecificEnergy(
        self, unit: str | None = None
    ) -> float: ...
    def SetAbt10ReferenceMinimumSpecificEnergy(
        self, value: str | float, unit: str | None = None
    ) -> None: ...
    def GetAbt10MinimumSpecificEnergy(self, unit: str | None = None) -> float: ...
    def SetAbt10MinimumSpecificEnergy(
        self, value: float, unit: str | None = None
    ) -> None: ...
    def GetAbt10ReferenceSize(self, unit: str | None = None) -> float: ...
    def SetAbt10ReferenceSize(
        self, value: str | float, unit: str | None = None
    ) -> None: ...
    def GetAbt10SelectFunctionCoefficient(self, unit: str | None = None) -> float: ...
    def SetAbt10SelectFunctionCoefficient(
        self, value: str | float, unit: str | None = None
    ) -> None: ...
    def GetDistributionModel(self) -> str: ...
    def SetDistributionModel(self, value: str) -> None: ...
    def GetValidDistributionModelValues(self) -> list[str]: ...
    def GetSurfaceEnergy(self, unit: str | None = None) -> float: ...
    def SetSurfaceEnergy(self, value: str | float, unit: str | None = None) -> None: ...
    def GetIncludeRotationalDeformations(self) -> bool: ...
    def SetIncludeRotationalDeformations(self, value: bool) -> None: ...
    def EnableIncludeRotationalDeformations(self) -> None: ...
    def DisableIncludeRotationalDeformations(self) -> None: ...
    def IsIncludeRotationalDeformationsEnabled(self) -> bool: ...
    def GetMinimumSize(self, unit: str | None = None) -> float: ...
    def SetMinimumSize(self, value: str | float, unit: str | None = None) -> None: ...
    def GetMinimumSizeRatio(self) -> float: ...
    def SetMinimumSizeRatio(self, value: str | float) -> None: ...
    def GetMinimumVolumeFractionForFragmentDisabling(self) -> float: ...
    def SetMinimumVolumeFractionForFragmentDisabling(
        self, value: str | float
    ) -> None: ...
    def GetTavaresA(self, unit: str | None = None) -> float: ...
    def SetTavaresA(self, value: str | float, unit: str | None = None) -> None: ...
    def GetTavaresB(self, unit: str | None = None) -> float: ...
    def SetTavaresB(self, value: str | float, unit: str | None = None) -> None: ...
    def GetTavaresD0(self, unit: str | None = None) -> float: ...
    def SetTavaresD0(self, value: str | float, unit: str | None = None) -> None: ...
    def GetTavaresEInf(self, unit: str | None = None) -> float: ...
    def SetTavaresEInf(self, value: str | float, unit: str | None = None) -> None: ...
    def GetTavaresGamma(self, unit: str | None = None) -> float: ...
    def SetTavaresGamma(self, value: str | float, unit: str | None = None) -> None: ...
    def GetTavaresMinimumEnergy(self, unit: str | None = None) -> float: ...
    def SetTavaresMinimumEnergy(
        self, value: str | float, unit: str | None = None
    ) -> None: ...
    def GetTavaresPhi(self, unit: str | None = None) -> float: ...
    def SetTavaresPhi(self, value: str | float, unit: str | None = None) -> None: ...
    def GetTavaresRatioEmax(self, unit: str | None = None) -> float: ...
    def SetTavaresRatioEmax(
        self, value: str | float, unit: str | None = None
    ) -> None: ...
    def GetRatioEnergyAfterBreakage(self, unit: str | None = None) -> float: ...
    def SetRatioEnergyAfterBreakage(
        self, value: str | float, unit: str | None = None
    ) -> None: ...
    def GetTavaresSigmaSquared(self, unit: str | None = None) -> float: ...
    def SetTavaresSigmaSquared(
        self, value: str | float, unit: str | None = None
    ) -> None: ...
    def GetT10Formula(self) -> str: ...
    def SetT10Formula(self, value: str) -> None: ...
    def GetValidT10FormulaValues(self) -> list[str]: ...
    def GetShearStressLimit(self, unit: str | None = None) -> float: ...
    def SetShearStressLimit(
        self, value: str | float, unit: str | None = None
    ) -> None: ...
    def GetTensileStressLimit(self, unit: str | None = None) -> float: ...
    def SetTensileStressLimit(
        self, value: str | float, unit: str | None = None
    ) -> None: ...
    def GetEnableBreakage(self) -> bool: ...
    def SetEnableBreakage(self, value: bool) -> None: ...
    def EnableBreakage(self) -> None: ...
    def DisableBreakage(self) -> None: ...
    def IsBreakageEnabled(self) -> bool: ...
    def GetVonMisesStressLimit(self, unit: str | None = None) -> float: ...
    def SetVonMisesStressLimit(
        self, value: str | float, unit: str | None = None
    ) -> None: ...
    def GetAllowSelfContacts(self) -> bool: ...
    def SetAllowSelfContacts(self, value: bool) -> None: ...
    def GetDeformationModel(self) -> str: ...
    def SetDeformationModel(self, value: str) -> None: ...
    def GetValidDeformationModelValues(self) -> list[str]: ...
    def GetInternalFriction(self) -> float: ...
    def SetInternalFriction(self, value: str | float) -> None: ...
    def GetPlasticLimit(self, unit: str | None = None) -> float: ...
    def SetPlasticLimit(self, value: str | float, unit: str | None = None) -> None: ...
    def GetFlexible(self) -> bool: ...
    def SetFlexible(self, value: bool) -> None: ...
    def GetCenterOfMassOffset(self, unit: str | None = None) -> list[float]: ...
    def SetCenterOfMassOffset(
        self, values: Sequence[str | float], unit: str | None = None
    ) -> None: ...
    def GetChangeMassProperties(self) -> bool: ...
    def SetChangeMassProperties(self, value: bool) -> None: ...
    def GetEnableRotations(self) -> bool: ...
    def SetEnableRotations(self, value: bool) -> None: ...
    def GetHorizontalAspectRatio(self) -> float: ...
    def SetHorizontalAspectRatio(self, value: str | float) -> None: ...
    def GetPrincipalMomentOfInertia(self, unit: str | None = None) -> list[float]: ...
    def SetPrincipalMomentOfInertia(
        self, values: Sequence[str | float], unit: str | None = None
    ) -> None: ...
    def GetNumberOfCorners(self) -> int: ...
    def SetNumberOfCorners(self, value: str | int) -> None: ...
    def GetXDirection(self, unit: str | None = None) -> list[float]: ...
    def SetXDirection(
        self, values: Sequence[str | float], unit: str | None = None
    ) -> None: ...
    def GetYDirection(self, unit: str | None = None) -> list[float]: ...
    def SetYDirection(
        self, values: Sequence[str | float], unit: str | None = None
    ) -> None: ...
    def GetZDirection(self, unit: str | None = None) -> list[float]: ...
    def SetZDirection(
        self, values: Sequence[str | float], unit: str | None = None
    ) -> None: ...
    def GetRollingResistance(self) -> float: ...
    def SetRollingResistance(self, value: str | float) -> None: ...
    def GetSideAngle(self) -> float: ...
    def SetSideAngle(self, value: str | float) -> None: ...
    def GetSmoothness(self) -> float: ...
    def SetSmoothness(self, value: str | float) -> None: ...
    def GetSuperquadricDegree(self) -> float: ...
    def SetSuperquadricDegree(self, value: str | float) -> None: ...
    def GetThickness(self, unit: str | None = None) -> float: ...
    def SetThickness(self, value: str | float, unit: str | None = None) -> None: ...
    def GetVerticalAspectRatio(self) -> float: ...
    def SetVerticalAspectRatio(self, value: str | float) -> None: ...
    def GetBendingAngleLimit(self, unit: str | None = None) -> float: ...
    def SetBendingAngleLimit(
        self, value: str | float, unit: str | None = None
    ) -> None: ...
    def GetWithFailure(self) -> bool: ...
    def SetWithFailure(self, value: bool) -> None: ...
    def GetEdgeAngle(self, unit: str | None = None) -> float: ...
    def SetEdgeAngle(self, value: str | float, unit: str | None = None) -> None: ...
    def GetElasticRatioBending(self) -> float: ...
    def SetElasticRatioBending(self, value: str | float) -> None: ...
    def GetElasticRatioNormal(self) -> float: ...
    def SetElasticRatioNormal(self, value: str | float) -> None: ...
    def GetElasticRatioTangential(self) -> float: ...
    def SetElasticRatioTangential(self, value: str | float) -> None: ...
    def GetElasticRatioTorsion(self) -> float: ...
    def SetElasticRatioTorsion(self, value: str | float) -> None: ...
    def GetElasticity(self) -> str: ...
    def SetElasticity(self, value: str) -> None: ...
    def GetValidElasticityValues(self) -> list[str]: ...
    def GetTargetNumberOfElements(self) -> int: ...
    def SetTargetNumberOfElements(self, value: str | int) -> None: ...
    def GetElementDampingRatio(self) -> float: ...
    def SetElementDampingRatio(self, value: str | float) -> None: ...
    def GetFailureRatio(self) -> float: ...
    def SetFailureRatio(self, value: str | float) -> None: ...
    def GetJointDampingRatio(self) -> float: ...
    def SetJointDampingRatio(self, value: str | float) -> None: ...
    def GetJointElasticRatio(self) -> float: ...
    def SetJointElasticRatio(self, value: str | float) -> None: ...
    def GetJointThermalRatio(self) -> float: ...
    def SetJointThermalRatio(self, value: str | float) -> None: ...
    def GetPlasticRatio(self) -> float: ...
    def SetPlasticRatio(self, value: str | float) -> None: ...
    def GetPlasticityModel(self) -> str: ...
    def SetPlasticityModel(self, value: str) -> None: ...
    def GetValidPlasticityModelValues(self) -> list[str]: ...
    def GetRemeshToTarget(self) -> bool: ...
    def SetRemeshToTarget(self, value: bool) -> None: ...
    def GetSecondBendingAngleLimit(self, unit: str | None = None) -> float: ...
    def SetSecondBendingAngleLimit(
        self, value: str | float, unit: str | None = None
    ) -> None: ...
    def GetTorsionAngleLimit(self, unit: str | None = None) -> float: ...
    def SetTorsionAngleLimit(
        self, value: str | float, unit: str | None = None
    ) -> None: ...
    def GetName(self) -> str: ...
    def SetName(self, value: str) -> None: ...
    def GetPorosity(self, unit: str | None = None) -> float: ...
    def SetPorosity(self, value: str | float, unit: str | None = None) -> None: ...
    def GetRandomAnglesHalfRange(self, unit: str | None = None) -> list[float]: ...
    def SetRandomAnglesHalfRange(
        self, values: Sequence[str | float], unit: str | None = None
    ) -> None: ...
    def GetShape(self) -> str: ...
    def SetShape(self, value: str) -> None: ...
    def GetValidShapeValues(self) -> list[str]: ...
    def GetCgmScaleFactor(self) -> float: ...
    def SetCgmScaleFactor(self, value: str | float) -> None: ...
    def GetSizeType(self) -> str: ...
    def SetSizeType(self, value: str) -> None: ...
    def GetValidSizeTypeValues(self) -> list[str]: ...
    def GetEnableRandomAngle(self) -> bool: ...
    def SetEnableRandomAngle(self, value: bool) -> None: ...
    def EnableRandomOrientation(self) -> None: ...
    def DisableRandomOrientation(self) -> None: ...
    def IsRandomOrientationEnabled(self) -> bool: ...
    def GetMaterial(self): ...
    def SetMaterial(self, value) -> None: ...
    def GetAvailableMaterials(self): ...
    def GetAnisotropic(self) -> bool: ...
    def SetAnisotropic(self, value: bool) -> None: ...
    GetPrincipalMomentOfInertia: Incomplete
    SetPrincipalMomentOfInertia: Incomplete
    GetXDirection: Incomplete
    SetXDirection: Incomplete
    GetYDirection: Incomplete
    SetYDirection: Incomplete
    GetZDirection: Incomplete
    SetZDirection: Incomplete
    GetPorosity: Incomplete
    SetPorosity: Incomplete
