from ansys.rocky.core._api_stubs.plugins10.plugins.api.api_element_item import ApiElementItem

class RAParametricVariables(ApiElementItem):
    @classmethod
    def GetWrappedClass(cls): ...
    @classmethod
    def GetClassName(cls): ...
    def GetInputVariables(self): ...
