# Copyright (C) 2023 - 2025 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

from ansys.rocky.core._api_stubs.plugins10.plugins.api.api_element_item import (
    ApiElementItem,
)
from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_api import (
    RockyApiError as RockyApiError,
)
from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_particle import (
    RAParticle as RAParticle,
)
from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_particle_inlet_properties import (
    RAParticleInletPropertiesList as RAParticleInletPropertiesList,
)

class RAParticleInlet(ApiElementItem):
    @classmethod
    def GetWrappedClass(self): ...
    @classmethod
    def GetClassName(self) -> str: ...
    def GetInputPropertiesList(self) -> RAParticleInletPropertiesList: ...
    def AddParticle(
        self, particle: RAParticle | str
    ) -> RAParticleInletPropertiesList: ...
    def RemoveParticle(self, particle: RAParticle | str) -> None: ...
    def GetName(self) -> str: ...
    def SetName(self, value: str) -> None: ...
    def GetInjectionDuration(self, unit: str | None = None) -> float: ...
    def SetInjectionDuration(
        self, value: str | float, unit: str | None = None
    ) -> None: ...
    def GetForcePacking(self) -> bool: ...
    def SetForcePacking(self, value: bool) -> None: ...
    def EnableForcePacking(self) -> None: ...
    def DisableForcePacking(self) -> None: ...
    def IsForcePackingEnabled(self) -> bool: ...
    def GetPeriod(self, unit: str | None = None) -> float: ...
    def SetPeriod(self, value: str | float, unit: str | None = None) -> None: ...
    def GetPeriodic(self) -> bool: ...
    def SetPeriodic(self, value: bool) -> None: ...
    def EnablePeriodic(self) -> None: ...
    def DisablePeriodic(self) -> None: ...
    def IsPeriodicEnabled(self) -> bool: ...
    def GetStartTime(self, unit: str | None = None) -> float: ...
    def SetStartTime(self, value: str | float, unit: str | None = None) -> None: ...
    def GetStopAllAtStopTime(self) -> bool: ...
    def SetStopAllAtStopTime(self, value: bool) -> None: ...
    def EnableStopAllAtStopTime(self) -> None: ...
    def DisableStopAllAtStopTime(self) -> None: ...
    def IsStopAllAtStopTimeEnabled(self) -> bool: ...
    def GetStopTime(self, unit: str | None = None) -> float: ...
    def SetStopTime(self, value: str | float, unit: str | None = None) -> None: ...
    def GetTargetNormalVelocity(self, unit: str | None = None) -> float: ...
    def SetTargetNormalVelocity(
        self, value: str | float, unit: str | None = None
    ) -> None: ...
    def GetUseTargetNormalVelocity(self) -> bool: ...
    def SetUseTargetNormalVelocity(self, value: bool) -> None: ...
    def EnableUseTargetNormalVelocity(self) -> None: ...
    def DisableUseTargetNormalVelocity(self) -> None: ...
    def IsUseTargetNormalVelocityEnabled(self) -> bool: ...
    def GetUxLocal(self, unit: str | None = None) -> float: ...
    def SetUxLocal(self, value: str | float, unit: str | None = None) -> None: ...
    def GetUzLocal(self, unit: str | None = None) -> float: ...
    def SetUzLocal(self, value: str | float, unit: str | None = None) -> None: ...
    def GetSphInjectionEnabled(self) -> bool: ...
    def SetSphInjectionEnabled(self, value: bool) -> None: ...
    def GetSphTemperature(self, unit: str | None = None) -> float: ...
    def SetSphTemperature(self, value: str | float, unit: str | None = None) -> None: ...
    def GetEntryPoint(self): ...
    def SetEntryPoint(self, value) -> None: ...
    def GetAvailableEntryPoints(self): ...
