# Copyright (C) 2023 - 2025 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

from collections.abc import Sequence

from rocky30.models.particle.particle_assembly import (
    ParticleAssemblyCustom as ParticleAssemblyCustom,
)
from rocky30.models.particle.particle_assembly import (
    ParticleAssemblyPart as ParticleAssemblyPart,
)
from rocky30.models.particle.particle_assembly import (
    ParticleAssemblyPartList as ParticleAssemblyPartList,
)

from ansys.rocky.core._api_stubs.plugins10.plugins.api.api_element_item import (
    ApiElementItem,
)
from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_list import RAList as RAList
from ansys.rocky.core._api_stubs.rocky30.plugins.api.rocky_api_deprecated_decorator import (
    ApiDeprecated as ApiDeprecated,
)

class RAParticleAssemblyPart(ApiElementItem):
    @classmethod
    def GetWrappedClass(self) -> type[ParticleAssemblyPart]: ...
    @classmethod
    def GetClassName(self): ...
    def GetAngle(self, unit: str | None = None) -> float: ...
    def SetAngle(self, value: str | float, unit: str | None = None) -> None: ...
    def GetPositionX(self, unit: str | None = None) -> float: ...
    def SetPositionX(self, value: str | float, unit: str | None = None) -> None: ...
    def GetPositionY(self, unit: str | None = None) -> float: ...
    def SetPositionY(self, value: str | float, unit: str | None = None) -> None: ...
    def GetPositionZ(self, unit: str | None = None) -> float: ...
    def SetPositionZ(self, value: str | float, unit: str | None = None) -> None: ...
    def GetRotationX(self, unit: str | None = None) -> float: ...
    def SetRotationX(self, value: str | float, unit: str | None = None) -> None: ...
    def GetRotationY(self, unit: str | None = None) -> float: ...
    def SetRotationY(self, value: str | float, unit: str | None = None) -> None: ...
    def GetRotationZ(self, unit: str | None = None) -> float: ...
    def SetRotationZ(self, value: str | float, unit: str | None = None) -> None: ...
    def GetScale(self, unit: str | None = None) -> float: ...
    def SetScale(self, value: str | float, unit: str | None = None) -> None: ...
    def GetParticle(self): ...
    def SetParticle(self, value) -> None: ...
    def GetAvailableParticles(self): ...

class RAParticleAssemblyPartList(RAList[RAParticleAssemblyPart]):
    @classmethod
    def GetWrappedClass(self) -> type[ParticleAssemblyPartList]: ...
    @classmethod
    def GetClassName(self) -> str: ...

class RAParticleAssemblyCustom(ApiElementItem):
    @classmethod
    def GetWrappedClass(self) -> type[ParticleAssemblyCustom]: ...
    @classmethod
    def GetClassName(self): ...
    def GetMomentOfInertia(self, unit: str | None = None) -> list[float]: ...
    def SetMomentOfInertia(
        self, values: Sequence[str | float], unit: str | None = None
    ) -> None: ...
    def GetArea(self, unit: str | None = None) -> float: ...
    def SetArea(self, value: str | float, unit: str | None = None) -> None: ...
    def GetCenterOfMass(self, unit: str | None = None) -> list[float]: ...
    def SetCenterOfMass(
        self, values: Sequence[str | float], unit: str | None = None
    ) -> None: ...
    def GetEnabled(self) -> bool: ...
    def SetEnabled(self, value: bool) -> None: ...
    def GetGeometricCenter(self, unit: str | None = None) -> list[float]: ...
    def SetGeometricCenter(
        self, values: Sequence[str | float], unit: str | None = None
    ) -> None: ...
    def GetInertiaXAxis(self, unit: str | None = None) -> list[float]: ...
    def SetInertiaXAxis(
        self, values: Sequence[str | float], unit: str | None = None
    ) -> None: ...
    def GetInertiaYAxis(self, unit: str | None = None) -> list[float]: ...
    def SetInertiaYAxis(
        self, values: Sequence[str | float], unit: str | None = None
    ) -> None: ...
    def GetInertiaZAxis(self, unit: str | None = None) -> list[float]: ...
    def SetInertiaZAxis(
        self, values: Sequence[str | float], unit: str | None = None
    ) -> None: ...
    def GetMass(self, unit: str | None = None) -> float: ...
    def SetMass(self, value: str | float, unit: str | None = None) -> None: ...
    def GetPrincipalMomentOfInertia(self, unit: str | None = None) -> list[float]: ...
    def SetPrincipalMomentOfInertia(
        self, values: Sequence[str | float], unit: str | None = None
    ) -> None: ...
    def GetPorosity(self, unit: str | None = None) -> float: ...
    def SetPorosity(self, value: str | float, unit: str | None = None) -> None: ...
    def GetVolume(self, unit: str | None = None) -> float: ...
    def SetVolume(self, value: str | float, unit: str | None = None) -> None: ...
