from _typeshed import Incomplete
from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_process_element import RAUserProcess as RAUserProcess

class RAParticleTimeSelectionProcess(RAUserProcess):
    @classmethod
    def GetWrappedClass(self): ...
    @classmethod
    def GetClassName(self): ...
    def SetAbsoluteTimeRange(self, initial_time, final_time, unit: str = ...) -> None: ...
    def SetTimeRange(self, range_definition: Incomplete | None = ..., initial: Incomplete | None = ..., final: Incomplete | None = ..., unit: str = ...) -> None: ...
    def GetTimeRange(self): ...
