from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_grid_process_element import RAGridProcessElementItem as RAGridProcessElementItem

class RAParticles(RAGridProcessElementItem):
    @classmethod
    def GetWrappedClass(self): ...
    @classmethod
    def GetClassName(self): ...
    def GetNumberOfParticles(self, time_step): ...
    def IterParticles(self, time_step): ...
    def RemoveProcess(self) -> None: ...
