# Copyright (C) 2023 - 2025 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

from collections.abc import Sequence

from coilib50.process.base_process_subject import (
    AbstractProcessSubject as AbstractProcessSubject,
)
from coilib50.time.time_step_interface import ITimeStep as ITimeStep
from coilib50.units import Scalar as Scalar
from kraken20.plugins.api.ka_element_item import KAElementItem
from oop_ext.foundation.decorators import Abstract
from rocky30.base_types import Tuple3F as Tuple3F
from rocky30.plugins.sph.surface_user_process.surface_user_process_subject import (
    SurfaceUserProcessSubject as SurfaceUserProcessSubject,
)
from rocky30.plugins.user_process.group.cube_process_group import (
    CubeProcessGroup as CubeProcessGroup,
)
from rocky30.plugins.user_process.group.cylinder_process_group import (
    CylinderProcessGroup as CylinderProcessGroup,
)
from rocky30.plugins.user_process.group.plane_process_group import (
    PlaneProcessGroup as PlaneProcessGroup,
)
from rocky30.plugins.user_process.process_factories.group_process_factory_constants import (
    CUBE_GROUP_CHILD_PROCESS_COMMAND_ID as CUBE_GROUP_CHILD_PROCESS_COMMAND_ID,
)
from rocky30.plugins.user_process.process_factories.group_process_factory_constants import (
    CYLINDER_GROUP_CHILD_PROCESS_COMMAND_ID as CYLINDER_GROUP_CHILD_PROCESS_COMMAND_ID,
)
from rocky30.plugins.user_process.process_factories.group_process_factory_constants import (
    PLANE_GROUP_CHILD_PROCESS_COMMAND_ID as PLANE_GROUP_CHILD_PROCESS_COMMAND_ID,
)
from rocky30.process.user_process.cube_process_with_movement import (
    CubeProcessWithMovement as CubeProcessWithMovement,
)
from rocky30.process.user_process.cylinder_process_with_movement import (
    CylinderProcessWithMovement as CylinderProcessWithMovement,
)
from rocky30.process.user_process.polyhedron_process_with_movement import (
    PolyhedronProcessWithMovement as PolyhedronProcessWithMovement,
)
from sci20.app.mesh_assembly.cube.abstract_cube import BaseCube as BaseCube
from sci20.app.mesh_assembly.cylinder.mesh_assembly_cylinder import (
    BaseCylinder as BaseCylinder,
)
from sci20.app.mesh_assembly.plane.mesh_assembly_plane_process import (
    BasePlane as BasePlane,
)
from sci20.plugins.api.api_process_element import SciApiProcessElementItem
from sci20.plugins.process.plane_process.plane_process_subject import PlaneProcessSubject

from ansys.rocky.core._api_stubs.rocky30.plugins.api._ra_orientation_mixin import (
    _RAOrientationMixin,
)
from ansys.rocky.core._api_stubs.rocky30.plugins.api.motion._with_movement_mixin import (
    _WithMovementMixin,
)
from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_grid_process_element import (
    RAGridProcessElementItem as RAGridProcessElementItem,
)

class RAProcessElementItem(SciApiProcessElementItem):
    def GetCurve(
        self, curve_name, simulation_name=None, realization=None, time_step=None
    ): ...

class RAUserProcess(RAGridProcessElementItem):
    def GetNumberOfParticles(self, time_step): ...
    def IterParticles(self, time_step): ...

class _RAAbstractCubeMixin:
    @Abstract
    def GetSubject(self) -> BaseCube: ...
    def GetCenter(self, unit=None): ...
    def SetCenter(
        self, x: float, y: float, z: float, unit: str | None = None
    ) -> None: ...
    def GetCenterAfterMovement(self, timestep: int) -> Tuple3F: ...
    def GetSize(self, unit: str | None = None) -> Tuple3F: ...
    def SetSize(self, x: float, y: float, z: float, unit: str | None = None): ...
    def GetRotation(self, unit=None): ...
    def SetRotation(self, x, y, z, unit=None): ...

class RACubeGroup(
    KAElementItem, _WithMovementMixin, _RAOrientationMixin, _RAAbstractCubeMixin
):
    @classmethod
    def GetWrappedClass(cls) -> type[CubeProcessGroup]: ...
    @classmethod
    def GetClassName(cls) -> str: ...
    def AddProcess(self, source_process: AbstractProcessSubject) -> None: ...

class _RAAbstractCylinderMixin:
    @Abstract
    def GetSubject(self) -> BaseCylinder: ...
    def GetCenter(self, unit=None): ...
    def SetCenter(
        self, x: float, y: float, z: float, unit: str | None = None
    ) -> None: ...
    def GetCenterAfterMovement(self, timestep: int) -> Tuple3F: ...
    def GetSize(self, unit: str | None = None) -> Tuple3F: ...
    def SetSize(self, x: float, y: float, z: float, unit: str | None = None) -> None: ...
    def GetRotation(self, unit=None): ...
    def SetRotation(self, x, y, z, unit=None): ...
    def GetInternalFactor(self, unit=None): ...
    def SetInternalFactor(self, internal_factor, unit=None) -> None: ...
    def GetInitialAngle(self, unit=None): ...
    def SetInitialAngle(self, initial_angle, unit=None) -> None: ...
    def GetFinalAngle(self, unit=None): ...
    def SetFinalAngle(self, final_angle, unit=None) -> None: ...

class RACylinderGroup(
    KAElementItem, _WithMovementMixin, _RAOrientationMixin, _RAAbstractCylinderMixin
):
    @classmethod
    def GetWrappedClass(cls) -> type[CylinderProcessGroup]: ...
    @classmethod
    def GetClassName(cls) -> str: ...
    def AddProcess(self, source_process: AbstractProcessSubject) -> None: ...

class RACubeProcess(
    RAUserProcess, _WithMovementMixin, _RAOrientationMixin, _RAAbstractCubeMixin
):
    @classmethod
    def GetWrappedClass(cls): ...
    @classmethod
    def GetClassName(cls): ...

class RACylinderProcess(
    RAUserProcess, _WithMovementMixin, _RAOrientationMixin, _RAAbstractCylinderMixin
):
    @classmethod
    def GetWrappedClass(self): ...
    @classmethod
    def GetClassName(self): ...

class RAFilterProcess(RAUserProcess):
    @classmethod
    def GetWrappedClass(self): ...
    @classmethod
    def GetClassName(self): ...
    def GetType(self): ...
    def SetType(self, filter_type) -> None: ...
    def GetMode(self): ...
    def SetMode(self, property_mode) -> None: ...
    def GetMinValue(self, unit=None): ...
    def SetMinValue(self, value, unit=None) -> None: ...
    def GetMaxValue(self, unit=None): ...
    def SetMaxValue(self, value, unit=None) -> None: ...
    def GetCutValue(self, unit=None): ...
    def SetCutValue(self, value, unit=None) -> None: ...
    def SetPropertyGridFunction(self, grid_function, realization=None) -> None: ...
    def GetPropertyGridFunction(self): ...

class _RAAbstractPlaneMixin:
    @Abstract
    def GetSubject(self) -> BasePlane: ...
    def GetType(self) -> str: ...
    def SetType(self, plane_type: str) -> None: ...
    def GetMode(self) -> str: ...
    def SetMode(self, plane_mode: str) -> None: ...
    def GetOrigin(self, unit=None) -> Tuple3F: ...
    def SetOrigin(self, x: float, y: float, z: float) -> None: ...

class RAPlaneProcess(RAUserProcess, _RAOrientationMixin, _RAAbstractPlaneMixin):
    @classmethod
    def GetWrappedClass(self) -> type[PlaneProcessSubject]: ...
    @classmethod
    def GetClassName(self) -> str: ...
    def SetRelativeRotationVector(self, x: float, y: float, z: float) -> None: ...
    def GetRelativeRotationVector(self) -> Tuple3F: ...

class RAPlaneGroup(KAElementItem, _RAOrientationMixin, _RAAbstractPlaneMixin):
    @classmethod
    def GetWrappedClass(cls) -> type[PlaneProcessGroup]: ...
    @classmethod
    def GetClassName(cls) -> str: ...
    def AddProcess(self, source_process: AbstractProcessSubject) -> None: ...

class RATrajectoryProcess(RAUserProcess):
    @classmethod
    def GetWrappedClass(self): ...
    @classmethod
    def GetClassName(self): ...
    def SetStartingTime(self, time: str | ITimeStep | int) -> None: ...
    def GetStartingTime(self) -> ITimeStep: ...
    def SetNumberOfIntervals(self, number_of_intervals: int): ...
    def GetNumberOfIntervals(self) -> int: ...
    def SetParticleStride(self, particle_stride) -> None: ...
    def GetParticleStride(self): ...
    def UpdateParticlesSelection(self) -> None: ...

class RAInspectorProcess(RAUserProcess):
    @classmethod
    def GetWrappedClass(self): ...
    @classmethod
    def GetClassName(self): ...
    def SetCellId(self, cell_id) -> None: ...

class RAPolyhedronProcess(RAUserProcess, _WithMovementMixin, _RAOrientationMixin):
    @classmethod
    def GetWrappedClass(cls) -> type[PolyhedronProcessWithMovement]: ...
    @classmethod
    def GetClassName(cls) -> str: ...
    def GetCenter(self, unit=None) -> Tuple3F: ...
    def SetCenter(
        self, x: float, y: float, z: float, unit: str | None = None
    ) -> None: ...
    def GetCenterAfterMovement(self, timestep: int) -> Tuple3F: ...
    def SetSTL(self, filename: str, mesh_unit: str | None = None) -> None: ...
    def GetName(self) -> str: ...
    def SetName(self, value: str) -> None: ...
    def GetScale(self, unit: str | None = None) -> list[float]: ...
    def SetScale(
        self, values: Sequence[str | float], unit: str | None = None
    ) -> None: ...

class RASurfaceUserProcess(RAUserProcess, _WithMovementMixin, _RAOrientationMixin):
    @classmethod
    def GetWrappedClass(cls) -> type["SurfaceUserProcessSubject"]: ...
    @classmethod
    def GetClassName(cls) -> str: ...
    def SetSTL(self, filename: str, mesh_unit: str | None = None) -> None: ...
    def GetCenter(self, unit: str | None = None) -> Tuple3F: ...
    def SetCenter(
        self, x: float, y: float, z: float, unit: str | None = None
    ) -> None: ...
    def GetName(self) -> str: ...
    def SetName(self, value: str) -> None: ...
    def GetScale(self, unit: str | None = None) -> list[float]: ...
    def SetScale(
        self, values: Sequence[str | float], unit: str | None = None
    ) -> None: ...
