from rocky30.models.regions_of_interest.roi_collection import RoiCollection as RoiCollection
from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_list import RAList as RAList
from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_region_of_interest_cube import RARegionOfInterestCube as RARegionOfInterestCube
from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_region_of_interest_cylinder import RARegionOfInterestCylinder as RARegionOfInterestCylinder

class RARegionsOfInterestCollection(RAList):
    @classmethod
    def GetWrappedClass(cls) -> type[RoiCollection]: ...
    @classmethod
    def GetClassName(cls) -> str: ...
    def AddCube(self, name: Union[str, None] = ...) -> RARegionOfInterestCube: ...
    def AddCylinder(self, name: Union[str, None] = ...) -> RARegionOfInterestCylinder: ...
