from ansys.rocky.core._api_stubs.plugins10.plugins.api.api_element_item import ApiElementItem
from rocky30.plugins.particles_calculations.selection_residence_time_calculation import ParticlesSelectionResidenceTimeCalculator as ParticlesSelectionResidenceTimeCalculator
from typing import Optional, Type, Union

class RAResidenceTime(ApiElementItem):
    @classmethod
    def GetWrappedClass(self) -> Type[ParticlesSelectionResidenceTimeCalculator]: ...
    @classmethod
    def GetClassName(self) -> str: ...
    def GetGridFunctionName(self) -> str: ...
    def GetCalculatorName(self) -> str: ...
    def GetNameMask(self) -> str: ...
    def SetNameMask(self, value: str) -> None: ...
    def GetStopTime(self, unit: Optional[str] = ...) -> float: ...
    def SetStopTime(self, value: Union[str, float], unit: Optional[str] = ...) -> None: ...
    def GetStartTime(self, unit: Optional[str] = ...) -> float: ...
    def SetStartTime(self, value: Union[str, float], unit: Optional[str] = ...) -> None: ...
