# Copyright (C) 2023 - 2025 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

from collections.abc import Sequence

from rocky30.models.solver.rocky_simulator_run import (
    RockySimulatorRun as RockySimulatorRun,
)

from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_grid_process_element import (
    RAGridProcessElementItem as RAGridProcessElementItem,
)
from ansys.rocky.core._api_stubs.rocky30.plugins.api.rocky_api_deprecated_decorator import (
    ApiDeprecated as ApiDeprecated,
)
from ansys.rocky.core._api_stubs.rocky30.plugins.api.rocky_api_utils import (
    ConvertUserPassedValueToScalar as ConvertUserPassedValueToScalar,
)

class RASimulatorRun(RAGridProcessElementItem):
    @classmethod
    def GetWrappedClass(self) -> type["RockySimulatorRun"]: ...
    @classmethod
    def GetClassName(self) -> str: ...
    def RemoveProcess(self) -> None: ...
    def SetTimeConfiguration(self, duration: float, time_interval: float) -> None: ...
    def HasFEMForcesEnabled(self) -> bool: ...
    def HasHtcCalculatedData(self) -> bool: ...
    def EnableHtcCalculator(self) -> None: ...
    def DisableHtcCalculator(self) -> None: ...
    def EnableFEMForces(self) -> None: ...
    def DisableFEMForces(self) -> None: ...
    def HasCompressedFileEnabled(self) -> bool: ...
    def GetTargetGpus(self) -> list[int]: ...
    def SetTargetGpus(self, gpus: list[int | str]) -> None: ...
    def GetFluentOutputsMultiplier(self) -> int: ...
    def SetFluentOutputsMultiplier(self, value: int) -> None: ...
    def GetAvailableOutputRoots(self) -> Sequence[str]: ...
    def GetAvailableOutputRootProperties(self, root_key: str) -> Sequence[str]: ...
    def GetOutputRootEnabled(self, root_key: str) -> bool: ...
    def SetOutputRootEnabled(self, root_key: str, enabled: bool) -> None: ...
    def GetOutputPropertyEnabled(self, root_key: str, property_name: str) -> bool: ...
    def SetOutputPropertyEnabled(
        self, root_key: str, property_name: str, enabled: bool
    ) -> None: ...
    def GetStandardOutputPropertyEnabled(self, *output_property: str) -> bool: ...
    def SetStandardOutputPropertyEnabled(
        self, *output_property: str, enabled: bool
    ) -> None: ...
    def GetModulesOutputPropertyEnabled(self, *output_property: str) -> bool: ...
    def SetModulesOutputPropertyEnabled(
        self, *output_property: str, enabled: bool
    ) -> None: ...
    @staticmethod
    def GetAvailableStandardOutputProperties() -> dict: ...
    @staticmethod
    def GetAvailableModulesOutputProperties() -> dict: ...
    def GetStandardOutputPropertiesData(self) -> dict: ...
    def SetStandardOutputPropertiesData(self, data_dict: dict) -> None: ...
    def GetModulesOutputPropertiesData(self) -> dict: ...
    def SetModulesOutputPropertiesData(self, data_dict: dict) -> None: ...
    def RestoreOutputPropertiesDefaults(self) -> None: ...
    def GetUseDpmBlockingEffectForSinglePhaseSimulations(self) -> bool: ...
    def SetUseDpmBlockingEffectForSinglePhaseSimulations(self, value: bool) -> None: ...
    def EnableDpmBlockingEffectForSinglePhaseSimulations(self) -> None: ...
    def DisableDpmBlockingEffectForSinglePhaseSimulations(self) -> None: ...
    def IsDpmBlockingEffectForSinglePhaseSimulationsEnabled(self) -> bool: ...
    def GetSimulationTarget(self) -> str: ...
    def SetSimulationTarget(self, value: str) -> None: ...
    def GetArraysGrowthRate(self) -> float: ...
    def SetArraysGrowthRate(self, value: str | float) -> None: ...
    def GetBreakageOverlapFactor(self) -> float: ...
    def SetBreakageOverlapFactor(self, value: str | float) -> None: ...
    def GetDisableTrianglesOnPeriodicBoundaries(self) -> bool: ...
    def SetDisableTrianglesOnPeriodicBoundaries(self, value: bool) -> None: ...
    def GetDragLimiterFactor(self) -> float: ...
    def SetDragLimiterFactor(self, value: str | float) -> None: ...
    def GetMoveCfdCellsWithRockyBoundaries(self) -> bool: ...
    def SetMoveCfdCellsWithRockyBoundaries(self, value: bool) -> None: ...
    def EnableMoveCfdCellsWithRockyBoundaries(self) -> None: ...
    def DisableMoveCfdCellsWithRockyBoundaries(self) -> None: ...
    def IsMoveCfdCellsWithRockyBoundariesEnabled(self) -> bool: ...
    def GetFixedTimestep(self, unit: str | None = None) -> float: ...
    def SetFixedTimestep(self, value: str | float, unit: str | None = None) -> None: ...
    def GetSuccessiveOverRelaxationTolerance(self) -> float: ...
    def SetSuccessiveOverRelaxationTolerance(self, value: str | float) -> None: ...
    def GetJointElasticRatio(self) -> float: ...
    def SetJointElasticRatio(self, value: str | float) -> None: ...
    def GetMinimumLengthDeformationTolerance(self) -> float: ...
    def SetMinimumLengthDeformationTolerance(self, value: str | float) -> None: ...
    def GetLinearHystDamp(self) -> float: ...
    def SetLinearHystDamp(self, value: str | float) -> None: ...
    def GetLoadingNSteps(self) -> int: ...
    def SetLoadingNSteps(self, value: str | int) -> None: ...
    def GetDeformableMassMatrixType(self) -> str: ...
    def SetDeformableMassMatrixType(self, value: str) -> None: ...
    def GetValidDeformableMassMatrixTypeValues(self) -> list[str]: ...
    def GetMinimumVolumeTolerance(self) -> float: ...
    def SetMinimumVolumeTolerance(self, value: str | float) -> None: ...
    def GetSolverCurvesFrequency(self) -> int: ...
    def SetSolverCurvesFrequency(self, value: str | int) -> None: ...
    def GetContactNeighboringDistanceBetweenParticles(
        self, unit: str | None = None
    ) -> float: ...
    def SetContactNeighboringDistanceBetweenParticles(
        self, value: str | float, unit: str | None = None
    ) -> None: ...
    def GetContactNeighboringDistanceBetweenParticlesAndTriangles(
        self, unit: str | None = None
    ) -> float: ...
    def SetContactNeighboringDistanceBetweenParticlesAndTriangles(
        self, value: str | float, unit: str | None = None
    ) -> None: ...
    def GetNegateInitialOverlaps(self) -> bool: ...
    def SetNegateInitialOverlaps(self, value: bool) -> None: ...
    def EnableNegateInitialOverlaps(self) -> None: ...
    def DisableNegateInitialOverlaps(self) -> None: ...
    def IsNegateInitialOverlapsEnabled(self) -> bool: ...
    def GetNeighborSearchModel(self) -> str: ...
    def SetNeighborSearchModel(self, value: str) -> None: ...
    def GetValidNeighborSearchModelValues(self) -> list[str]: ...
    def GetMaximumNumberOfIterations(self) -> int: ...
    def SetMaximumNumberOfIterations(self, value: str | int) -> None: ...
    def GetOverRelaxationCoefficient(self) -> float: ...
    def SetOverRelaxationCoefficient(self, value: str | float) -> None: ...
    def GetRefineConcaveSearch(self) -> bool: ...
    def SetRefineConcaveSearch(self, value: bool) -> None: ...
    def GetParticleSizeLimitForReordering(self, unit: str | None = None) -> float: ...
    def SetParticleSizeLimitForReordering(
        self, value: str | float, unit: str | None = None
    ) -> None: ...
    def GetSpecialReorderingForWidePsd(self) -> bool: ...
    def SetSpecialReorderingForWidePsd(self, value: bool) -> None: ...
    def GetResetOnlyPhysicalContactsData(self) -> bool: ...
    def SetResetOnlyPhysicalContactsData(self, value: bool) -> None: ...
    def GetSortingDistanceFactor(self) -> float: ...
    def SetSortingDistanceFactor(self, value: str | float) -> None: ...
    def GetTimestepModel(self) -> str: ...
    def SetTimestepModel(self, value: str) -> None: ...
    def GetValidTimestepModelValues(self) -> list[str]: ...
    def GetUse2023R2SourceTermsApproach(self) -> bool: ...
    def SetUse2023R2SourceTermsApproach(self, value: bool) -> None: ...
    def GetUse2023R2CellVolumeFractionUpdateApproach(self) -> bool: ...
    def SetUse2023R2CellVolumeFractionUpdateApproach(self, value: bool) -> None: ...
    def GetUseArraysGrowthRate(self) -> bool: ...
    def SetUseArraysGrowthRate(self, value: bool) -> None: ...
    def GetUseBreakageOverlapFactor(self) -> bool: ...
    def SetUseBreakageOverlapFactor(self, value: bool) -> None: ...
    def GetUse3RdPowerForCfdCgm(self) -> bool: ...
    def SetUse3RdPowerForCfdCgm(self, value: bool) -> None: ...
    def EnableUse3RdPowerForCfdCgm(self) -> None: ...
    def DisableUse3RdPowerForCfdCgm(self) -> None: ...
    def IsUse3RdPowerForCfdCgmEnabled(self) -> bool: ...
    def GetUseDragLimiterFactor(self) -> bool: ...
    def SetUseDragLimiterFactor(self, value: bool) -> None: ...
    def GetUseFixedTimestep(self) -> bool: ...
    def SetUseFixedTimestep(self, value: bool) -> None: ...
    def GetUseContactNeighboringDistanceBetweenParticles(self) -> bool: ...
    def SetUseContactNeighboringDistanceBetweenParticles(self, value: bool) -> None: ...
    def GetUseContactNeighboringDistanceBetweenParticlesAndTriangles(self) -> bool: ...
    def SetUseContactNeighboringDistanceBetweenParticlesAndTriangles(
        self, value: bool
    ) -> None: ...
    def GetUseNonRoundTorqueCorrection(self) -> bool: ...
    def SetUseNonRoundTorqueCorrection(self, value: bool) -> None: ...
    def GetUseSortingDistanceFactor(self) -> bool: ...
    def SetUseSortingDistanceFactor(self, value: bool) -> None: ...
    def EnableSortingDistanceFactor(self) -> None: ...
    def DisableSortingDistanceFactor(self) -> None: ...
    def IsSortingDistanceFactorEnabled(self) -> bool: ...
    def GetUseCompressedFiles(self) -> bool: ...
    def SetUseCompressedFiles(self, value: bool) -> None: ...
    def EnableCompressedFile(self) -> None: ...
    def DisableCompressedFile(self) -> None: ...
    def IsCompressedFileEnabled(self) -> bool: ...
    def GetMpiHeterogeneous(self) -> bool: ...
    def SetMpiHeterogeneous(self, value: bool) -> None: ...
    def GetMpiHostfile(self) -> str: ...
    def SetMpiHostfile(self, value: str) -> None: ...
    def GetMpiHosts(self) -> str: ...
    def SetMpiHosts(self, value: str) -> None: ...
    def GetMpiNumberOfProcesses(self) -> int: ...
    def SetMpiNumberOfProcesses(self, value: str | int) -> None: ...
    def GetMpiNumberOfThreads(self) -> int: ...
    def SetMpiNumberOfThreads(self, value: str | int) -> None: ...
    def GetMpiWithinScheduler(self) -> bool: ...
    def SetMpiWithinScheduler(self, value: bool) -> None: ...
    def GetMultiGpuSlicingDirection(self) -> str: ...
    def SetMultiGpuSlicingDirection(self, value: str) -> None: ...
    def GetValidMultiGpuSlicingDirectionValues(self) -> list[str]: ...
    def GetNumberOfProcessors(self) -> int: ...
    def SetNumberOfProcessors(self, value: str | int) -> None: ...
    def GetProcessingUnit(self) -> str: ...
    def SetProcessingUnit(self, value: str) -> None: ...
    def GetValidProcessingUnitValues(self) -> list[str]: ...
    def GetReleaseParticlesWithoutOverlapCheck(self) -> bool: ...
    def SetReleaseParticlesWithoutOverlapCheck(self, value: bool) -> None: ...
    def GetTargetGpu(self) -> int: ...
    def SetTargetGpu(self, value: str | int) -> None: ...
    def GetUseMpi(self) -> bool: ...
    def SetUseMpi(self, value: bool) -> None: ...
    def GetResumeDataFrequency(self) -> int: ...
    def SetResumeDataFrequency(self, value: str | int) -> None: ...
    def GetBreakageDelayAfterRelease(self, unit: str | None = None) -> float: ...
    def SetBreakageDelayAfterRelease(
        self, value: str | float, unit: str | None = None
    ) -> None: ...
    def GetBreakageStart(self, unit: str | None = None) -> float: ...
    def SetBreakageStart(self, value: str | float, unit: str | None = None) -> None: ...
    def GetTimeInterval(self, unit: str | None = None) -> float: ...
    def SetTimeInterval(self, value: str | float, unit: str | None = None) -> None: ...
    def GetOverlapParticlesDelay(self, unit: str | None = None) -> float: ...
    def SetOverlapParticlesDelay(
        self, value: str | float, unit: str | None = None
    ) -> None: ...
    def GetSimulationDuration(self, unit: str | None = None) -> float: ...
    def SetSimulationDuration(
        self, value: str | float, unit: str | None = None
    ) -> None: ...
    def GetWearGeometryUpdateInterval(self, unit: str | None = None) -> float: ...
    def SetWearGeometryUpdateInterval(
        self, value: str | float, unit: str | None = None
    ) -> None: ...
    def GetWearStart(self, unit: str | None = None) -> float: ...
    def SetWearStart(self, value: str | float, unit: str | None = None) -> None: ...
