from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_base_tagging import RABaseTagging as RABaseTagging
from rocky30.plugins.sph.calculations.tagging.sph_tagging_calculator import SPHTaggingCalculator as SPHTaggingCalculator
from typing import Union

class RASPHTagging(RABaseTagging):
    @classmethod
    def GetWrappedClass(self) -> type[SPHTaggingCalculator]: ...
    @classmethod
    def GetClassName(self) -> str: ...
    def GetNameMask(self) -> str: ...
    def SetNameMask(self, value: str) -> None: ...
    def GetTagValue(self) -> int: ...
    def SetTagValue(self, value: Union[str, int]) -> None: ...
