from ansys.rocky.core._api_stubs.plugins10.plugins.api.api_element_item import ApiElementItem
from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_list import RAList as RAList
from typing import List, Optional, Union

class RASizeDistribution(ApiElementItem):
    @classmethod
    def GetWrappedClass(self): ...
    @classmethod
    def GetClassName(self): ...
    def GetCumulativePercentage(self) -> float: ...
    def SetCumulativePercentage(self, value: Union[str, float]) -> None: ...
    def GetScaleFactor(self, unit: Optional[str] = ...) -> float: ...
    def SetScaleFactor(self, value: Union[str, float], unit: Optional[str] = ...) -> None: ...
    def GetSize(self, unit: Optional[str] = ...) -> float: ...
    def SetSize(self, value: Union[str, float], unit: Optional[str] = ...) -> None: ...

class RASizeDistributionList(RAList[RASizeDistribution]):
    @classmethod
    def GetWrappedClass(self): ...
    @classmethod
    def GetClassName(self): ...
    def GetCgmScaleFactor(self) -> float: ...
    def SetCgmScaleFactor(self, value: Union[str, float]) -> None: ...
    def GetSizeType(self) -> str: ...
    def SetSizeType(self, value: str) -> None: ...
    def GetValidSizeTypeValues(self) -> List[str]: ...
