# Copyright (C) 2023 - 2025 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

from rocky30.models.sph.sph_settings import SPHProcess as SPHProcess

from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_grid_process_element import (
    RAGridProcessElementItem as RAGridProcessElementItem,
)

class RASPHSettings(RAGridProcessElementItem):
    def __init__(self, id, model_id=None) -> None: ...
    @classmethod
    def GetWrappedClass(self) -> type[SPHProcess]: ...
    @classmethod
    def GetClassName(self) -> str: ...
    def SetSolver(self, value: str) -> None: ...
    def GetSolver(self) -> str: ...
    def GetCS(self) -> float: ...
    def SetCS(self, value: str | float) -> None: ...
    def GetClearyFactor(self) -> float: ...
    def SetClearyFactor(self, value: str | float) -> None: ...
    def GetDensityDevMinus(self) -> float: ...
    def SetDensityDevMinus(self, value: str | float) -> None: ...
    def GetDensityDevPlus(self) -> float: ...
    def SetDensityDevPlus(self, value: str | float) -> None: ...
    def GetDensityRelativeErrorTolerance(self) -> float: ...
    def SetDensityRelativeErrorTolerance(self, value: str | float) -> None: ...
    def GetDissFactor(self) -> float: ...
    def SetDissFactor(self, value: str | float) -> None: ...
    def GetDistFactorNorm(self) -> float: ...
    def SetDistFactorNorm(self, value: str | float) -> None: ...
    def GetDistFactorTang(self) -> float: ...
    def SetDistFactorTang(self, value: str | float) -> None: ...
    def GetEnabled(self) -> bool: ...
    def SetEnabled(self, value: bool) -> None: ...
    def GetEulerianSolutionEnabled(self) -> bool: ...
    def SetEulerianSolutionEnabled(self, value: bool) -> None: ...
    def EnableEulerianSolution(self) -> None: ...
    def DisableEulerianSolution(self) -> None: ...
    def IsEulerianSolutionEnabled(self) -> bool: ...
    def GetFreeSurfaceDivergenceLimit(self) -> float: ...
    def SetFreeSurfaceDivergenceLimit(self, value: str | float) -> None: ...
    def GetIncompressibilityRelaxationFactor(self) -> float: ...
    def SetIncompressibilityRelaxationFactor(self, value: str | float) -> None: ...
    def GetKernelDistFactor(self) -> float: ...
    def SetKernelDistFactor(self, value: str | float) -> None: ...
    def GetKernelType(self) -> str: ...
    def SetKernelType(self, value: str) -> None: ...
    def GetValidKernelTypeValues(self) -> list[str]: ...
    def GetLimitTurbulentViscosity(self) -> bool: ...
    def SetLimitTurbulentViscosity(self, value: bool) -> None: ...
    def GetMaximumExpectedVelocity(self, unit: str | None = None) -> float: ...
    def SetMaximumExpectedVelocity(
        self, value: str | float, unit: str | None = None
    ) -> None: ...
    def GetMaximumNumberOfIterations(self) -> int: ...
    def SetMaximumNumberOfIterations(self, value: str | int) -> None: ...
    def GetMinDistFactor(self) -> float: ...
    def SetMinDistFactor(self, value: str | float) -> None: ...
    def GetName(self) -> str: ...
    def SetName(self, value: str) -> None: ...
    def GetNegativePressureFactor(self) -> float: ...
    def SetNegativePressureFactor(self, value: str | float) -> None: ...
    def GetNumCellSteps(self) -> int: ...
    def SetNumCellSteps(self, value: str | int) -> None: ...
    def GetNumberOfSteps(self) -> int: ...
    def SetNumberOfSteps(self, value: str | int) -> None: ...
    def GetPosCorrectionType(self) -> str: ...
    def SetPosCorrectionType(self, value: str) -> None: ...
    def GetValidPosCorrectionTypeValues(self) -> list[str]: ...
    def GetPressureDeg(self) -> int: ...
    def SetPressureDeg(self, value: str | int) -> None: ...
    def GetPressureUnderRelaxationFactor(self) -> float: ...
    def SetPressureUnderRelaxationFactor(self, value: str | float) -> None: ...
    def GetRelaxedIncompressibilityConstraintEnabled(self) -> bool: ...
    def SetRelaxedIncompressibilityConstraintEnabled(self, value: bool) -> None: ...
    def EnableRelaxedIncompressibilityConstraint(self) -> None: ...
    def DisableRelaxedIncompressibilityConstraint(self) -> None: ...
    def IsRelaxedIncompressibilityConstraintEnabled(self) -> bool: ...
    def GetShepardFilterOnDensityEnabled(self) -> bool: ...
    def SetShepardFilterOnDensityEnabled(self, value: bool) -> None: ...
    def EnableShepardFilterOnDensity(self) -> None: ...
    def DisableShepardFilterOnDensity(self) -> None: ...
    def IsShepardFilterOnDensityEnabled(self) -> bool: ...
    def GetShepardFilterOnPressureEnabled(self) -> bool: ...
    def SetShepardFilterOnPressureEnabled(self, value: bool) -> None: ...
    def EnableShepardFilterOnPressure(self) -> None: ...
    def DisableShepardFilterOnPressure(self) -> None: ...
    def IsShepardFilterOnPressureEnabled(self) -> bool: ...
    def GetShiftingFactor(self) -> float: ...
    def SetShiftingFactor(self, value: str | float) -> None: ...
    def GetSize(self, unit: str | None = None) -> float: ...
    def SetSize(self, value: str | float, unit: str | None = None) -> None: ...
    def GetSolverModel(self) -> str: ...
    def SetSolverModel(self, value: str) -> None: ...
    def GetValidSolverModelValues(self) -> list[str]: ...
    def GetSoundSpeed(self, unit: str | None = None) -> float: ...
    def SetSoundSpeed(self, value: str | float, unit: str | None = None) -> None: ...
    def GetStabilityDegree(self) -> int: ...
    def SetStabilityDegree(self, value: str | int) -> None: ...
    def GetStabilityNegFactor(self) -> float: ...
    def SetStabilityNegFactor(self, value: str | float) -> None: ...
    def GetStabilityPosFactor(self) -> float: ...
    def SetStabilityPosFactor(self, value: str | float) -> None: ...
    def GetStiffFactor(self) -> float: ...
    def SetStiffFactor(self, value: str | float) -> None: ...
    def GetSurfaceTensionBoundaryAngle(self, unit: str | None = None) -> float: ...
    def SetSurfaceTensionBoundaryAngle(
        self, value: str | float, unit: str | None = None
    ) -> None: ...
    def GetSurfaceTensionBoundaryFraction(self) -> float: ...
    def SetSurfaceTensionBoundaryFraction(self, value: str | float) -> None: ...
    def GetSurfaceTensionCoefficient(self, unit: str | None = None) -> float: ...
    def SetSurfaceTensionCoefficient(
        self, value: str | float, unit: str | None = None
    ) -> None: ...
    def GetSurfaceTensionType(self) -> str: ...
    def SetSurfaceTensionType(self, value: str) -> None: ...
    def GetValidSurfaceTensionTypeValues(self) -> list[str]: ...
    def GetTimestepFactor(self) -> float: ...
    def SetTimestepFactor(self, value: str | float) -> None: ...
    def GetTurbDistanceFraction(self) -> float: ...
    def SetTurbDistanceFraction(self, value: str | float) -> None: ...
    def GetTurbulenceType(self) -> str: ...
    def SetTurbulenceType(self, value: str) -> None: ...
    def GetValidTurbulenceTypeValues(self) -> list[str]: ...
    def GetTurbulentPrandtl(self) -> float: ...
    def SetTurbulentPrandtl(self, value: str | float) -> None: ...
    def GetTurbulentViscosityMaximumRatio(self) -> float: ...
    def SetTurbulentViscosityMaximumRatio(self, value: str | float) -> None: ...
    def GetUpdateCoupledDensity(self) -> bool: ...
    def SetUpdateCoupledDensity(self, value: bool) -> None: ...
    def GetUseParticlesNeighborsList(self) -> bool: ...
    def SetUseParticlesNeighborsList(self, value: bool) -> None: ...
    def GetViscosityType(self) -> str: ...
    def SetViscosityType(self, value: str) -> None: ...
    def GetValidViscosityTypeValues(self) -> list[str]: ...
    def GetViscousForceIntegration(self) -> str: ...
    def SetViscousForceIntegration(self, value: str) -> None: ...
    def GetValidViscousForceIntegrationValues(self) -> list[str]: ...
    def GetViscousForceMaximumNumberOfIterations(self) -> int: ...
    def SetViscousForceMaximumNumberOfIterations(self, value: str | int) -> None: ...
    def GetViscousForceRelativeErrorTolerance(self) -> float: ...
    def SetViscousForceRelativeErrorTolerance(self, value: str | float) -> None: ...
    def GetViscousForceUnderRelaxationFactor(self) -> float: ...
    def SetViscousForceUnderRelaxationFactor(self, value: str | float) -> None: ...
    def GetXsphFactor(self) -> float: ...
    def SetXsphFactor(self, value: str | float) -> None: ...
    def GetFluidMaterial(self): ...
    def SetFluidMaterial(self, value) -> None: ...
    def GetAvailableFluidMaterials(self): ...
