from ansys.rocky.core._api_stubs.plugins10.plugins.api.api_element_item import ApiElementItem
from rocky30.models.sph.sph_eulerian_solution import SPHEulerianSolution as SPHEulerianSolution
from ansys.rocky.core._api_stubs.rocky30.plugins.api._ra_subject_with_coloring_mixin import _RASubjectWithColoringMixin
from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_sph_settings import RASPHSettings as RASPHSettings

class RASPHEulerianSolution(ApiElementItem, _RASubjectWithColoringMixin):
    @classmethod
    def GetWrappedClass(self): ...
    @classmethod
    def GetClassName(self) -> str: ...
    def GetEulerianSolutionEnabled(self) -> bool: ...
    def SetEulerianSolutionEnabled(self, value: bool) -> None: ...
    def EnableEulerianSolution(self) -> None: ...
    def DisableEulerianSolution(self) -> None: ...
    def IsEulerianSolutionEnabled(self) -> bool: ...
