from ansys.rocky.core._api_stubs.plugins10.plugins.api.api_element_item import ApiElementItem
from typing import Optional, Union

class RATimeRangeFilter(ApiElementItem):
    @classmethod
    def GetWrappedClass(self): ...
    @classmethod
    def GetClassName(self) -> str: ...
    def GetDomainRange(self) -> str: ...
    def SetDomainRange(self, value: str): ...
    def GetValidDomainRangeValues(self) -> list[str]: ...
    def GetFinal(self, unit: Optional[str] = ...) -> float: ...
    def SetFinal(self, value: Union[str, float], unit: Optional[str] = ...) -> None: ...
    def GetInitial(self, unit: Optional[str] = ...) -> float: ...
    def SetInitial(self, value: Union[str, float], unit: Optional[str] = ...) -> None: ...
