from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_base_tagging import RABaseTagging as RABaseTagging
from typing import Union

class RATagging(RABaseTagging):
    @classmethod
    def GetWrappedClass(self): ...
    @classmethod
    def GetClassName(self): ...
    def GetNameMask(self) -> str: ...
    def SetNameMask(self, value: str) -> None: ...
    def GetTagValue(self) -> int: ...
    def SetTagValue(self, value: Union[str, int]) -> None: ...
