from _typeshed import Incomplete
from ansys.rocky.core._api_stubs.plugins10.plugins.api.api_element_item import ApiElementItem
from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_base_subject_element import BaseSubjectApiElement as BaseSubjectApiElement

class RATimeStatisticsCalculator(BaseSubjectApiElement):
    def GetStartTime(self): ...
    def SetStartTime(self, time_value) -> None: ...
    def GetStopTime(self): ...
    def SetStopTime(self, time_value) -> None: ...
    def GetGridFunctionName(self): ...

class RATimeStatistics(ApiElementItem):
    def __init__(self, id, ra_process, model_id: Incomplete | None = ...) -> None: ...
    def AddGridFunction(self, start_time, stop_time, operation, grid_function_name, location: Incomplete | None = ...): ...
    def RemoveGridFunction(self, name_or_calculator) -> None: ...
    @classmethod
    def GetWrappedClass(self): ...
    @classmethod
    def GetClassName(self): ...
    @classmethod
    def CreateFor(self, ra_process): ...
