from ansys.rocky.core._api_stubs.plugins10.plugins.api.api_element_item import ApiElementItem

class RATimeFilter(ApiElementItem):
    @classmethod
    def GetWrappedClass(self): ...
    @classmethod
    def GetClassName(self): ...
    def GetFinalTime(self, unit: Union[str, None] = ...) -> float: ...
    def SetFinalTime(self, value: Union[str, float], unit: Union[str, None] = ...) -> None: ...
    def GetInitialTime(self, unit: Union[str, None] = ...) -> float: ...
    def SetInitialTime(self, value: Union[str, float], unit: Union[str, None] = ...) -> None: ...
    def GetEnabled(self) -> bool: ...
    def SetEnabled(self, value: bool) -> None: ...
    def EnableTimeFilter(self) -> None: ...
    def DisableTimeFilter(self) -> None: ...
    def IsTimeFilterEnabled(self) -> bool: ...
    def GetName(self) -> str: ...
    def SetName(self, value: str) -> None: ...
