# Copyright (C) 2023 - 2025 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

from collections.abc import Sequence

from rocky30.models.input.volume_fill import VolumeFill as VolumeFill

from ansys.rocky.core._api_stubs.plugins10.plugins.api.api_element_item import (
    ApiElementItem,
)
from ansys.rocky.core._api_stubs.rocky30.plugins.api._ra_orientation_mixin import (
    _RAOrientationMixin,
)
from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_api import (
    RockyApiError as RockyApiError,
)
from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_particle import (
    RAParticle as RAParticle,
)
from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_volumetric_inlet_properties import (
    RAVolumetricInletProperties as RAVolumetricInletProperties,
)
from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_volumetric_inlet_properties import (
    RAVolumetricInletPropertiesList as RAVolumetricInletPropertiesList,
)
from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_wall import RAWall as RAWall

class RAVolumetricInlet(ApiElementItem, _RAOrientationMixin):
    @classmethod
    def GetWrappedClass(self) -> type[VolumeFill]: ...
    @classmethod
    def GetClassName(self) -> str: ...
    def GetInputPropertiesList(self) -> RAVolumetricInletPropertiesList: ...
    def AddParticle(self, particle: RAParticle | str) -> RAVolumetricInletProperties: ...
    def RemoveParticle(self, particle: RAParticle | str) -> None: ...
    def GetBoxCenter(self, unit: str | None = None) -> list[float]: ...
    def SetBoxCenter(
        self, values: Sequence[str | float], unit: str | None = None
    ) -> None: ...
    def GetBoxDimensions(self, unit: str | None = None) -> list[float]: ...
    def SetBoxDimensions(
        self, values: Sequence[str | float], unit: str | None = None
    ) -> None: ...
    def GetUseGeometriesToCompute(self) -> bool: ...
    def SetUseGeometriesToCompute(self, value: bool) -> None: ...
    def GetGapScaleFactor(self) -> float: ...
    def SetGapScaleFactor(self, value: str | float) -> None: ...
    def GetInitialVelocity(self, unit: str | None = None) -> list[float]: ...
    def SetInitialVelocity(
        self, values: Sequence[str | float], unit: str | None = None
    ) -> None: ...
    def GetPeriodic(self) -> bool: ...
    def SetPeriodic(self, value: bool) -> None: ...
    def EnablePeriodic(self) -> None: ...
    def DisablePeriodic(self) -> None: ...
    def IsPeriodicEnabled(self) -> bool: ...
    def GetName(self) -> str: ...
    def SetName(self, value: str) -> None: ...
    def GetPeriod(self, unit: str | None = None) -> float: ...
    def SetPeriod(self, value: str | float, unit: str | None = None) -> None: ...
    def GetSeedCoordinates(self, unit: str | None = None) -> list[float]: ...
    def SetSeedCoordinates(
        self, values: Sequence[str | float], unit: str | None = None
    ) -> None: ...
    def GetInjectionTime(self, unit: str | None = None) -> float: ...
    def SetInjectionTime(self, value: str | float, unit: str | None = None) -> None: ...
    def GetStopTime(self, unit: str | None = None) -> float: ...
    def SetStopTime(self, value: str | float, unit: str | None = None) -> None: ...
    def GetSphMass(self, unit: str | None = None) -> float: ...
    def SetSphMass(self, value: str | float, unit: str | None = None) -> None: ...
    def GetSphTemperature(self, unit: str | None = None) -> float: ...
    def SetSphTemperature(self, value: str | float, unit: str | None = None) -> None: ...
    def GetUseBoxCenterAsSeedPoint(self) -> bool: ...
    def SetUseBoxCenterAsSeedPoint(self, value: bool) -> None: ...
    def EnableUseBoxCenterAsSeedPoint(self) -> None: ...
    def DisableUseBoxCenterAsSeedPoint(self) -> None: ...
    def IsUseBoxCenterAsSeedPointEnabled(self) -> bool: ...
    def GetGeometries(self): ...
    def SetGeometries(self, values) -> None: ...
    def GetAvailableGeometries(self): ...
