from ansys.rocky.core._api_stubs.plugins10.plugins.api.api_element_item import ApiElementItem
from rocky30.models.input.volume_fill import VolumeFillProperties as VolumeFillProperties, VolumeFillPropertiesList as VolumeFillPropertiesList
from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_addins import ElementWithAddins as ElementWithAddins
from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_list import RAList as RAList
from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_particle import RAParticle as RAParticle
from typing import Optional, Union

class RAVolumetricInletProperties(ApiElementItem, ElementWithAddins):
    @classmethod
    def GetWrappedClass(self) -> type[VolumeFillProperties]: ...
    @classmethod
    def GetClassName(self) -> str: ...
    def GetMass(self, unit: Optional[str] = ...) -> float: ...
    def SetMass(self, value: Union[str, float], unit: Optional[str] = ...) -> None: ...
    def GetTemperature(self, unit: Optional[str] = ...) -> float: ...
    def SetTemperature(self, value: Union[str, float], unit: Optional[str] = ...) -> None: ...
    def GetParticle(self): ...
    def SetParticle(self, value) -> None: ...
    def GetAvailableParticles(self): ...

class RAVolumetricInletPropertiesList(RAList[RAVolumetricInletProperties]):
    @classmethod
    def GetWrappedClass(self) -> type[VolumeFillPropertiesList]: ...
    @classmethod
    def GetClassName(self) -> str: ...
