# Copyright (C) 2023 - 2025 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

from collections.abc import Sequence

from rocky30.base_types import Tuple3F as Tuple3F
from rocky30.core.geometry.rocky_document_constants import (
    UNIT_PLANE_ANGLE as UNIT_PLANE_ANGLE,
)

from ansys.rocky.core._api_stubs.rocky30.plugins.api.motion._with_movement_mixin import (
    _WithMovementMixin,
)
from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_addins import (
    ElementWithAddins as ElementWithAddins,
)
from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_base_geometry import (
    RABaseGeometry as RABaseGeometry,
)
from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_project import (
    RAProject as RAProject,
)

class RAWall(RABaseGeometry, ElementWithAddins, _WithMovementMixin):
    @classmethod
    def GetWrappedClass(self): ...
    @classmethod
    def GetClassName(self) -> str: ...
    def LoadFile(
        self, file_path: str, import_scale: float = 1.0, convert_yz: bool = False
    ) -> None: ...
    def HasMotionFrame(self) -> bool: ...
    def GetOrientation(self, unit: str = ...) -> Tuple3F: ...
    def SetOrientation(self, rotation: Tuple3F, unit: str = ...) -> None: ...
    def SetOrientationFromAngles(
        self,
        rotation: Tuple3F,
        unit: str = ...,
        local_angles: bool = True,
        order: str = "XYZ",
    ) -> None: ...
    def SetOrientationFromAngleAndVector(
        self, angle: float, vector: Tuple3F, unit: str = ...
    ) -> None: ...
    def SetOrientationFromBasisVector(
        self, vector_x: Tuple3F, vector_y: Tuple3F, vector_z: Tuple3F
    ) -> None: ...
    def GetOrientationFromAngles(self, unit: str = ...) -> Tuple3F: ...
    def GetOrientationFromAngleAndVector(
        self, unit: str = ...
    ) -> tuple[float, Tuple3F]: ...
    def GetOrientationFromBasisVector(self) -> tuple[Tuple3F, Tuple3F, Tuple3F]: ...
    def GetCapillaryFrictionCoefficient(self) -> float: ...
    def SetCapillaryFrictionCoefficient(self, value: str | float) -> None: ...
    def GetDisableTime(self, unit: str | None = None) -> float: ...
    def SetDisableTime(self, value: str | float, unit: str | None = None) -> None: ...
    def GetEnableTime(self, unit: str | None = None) -> float: ...
    def SetEnableTime(self, value: str | float, unit: str | None = None) -> None: ...
    def GetPivotPoint(self, unit: str | None = None) -> list[float]: ...
    def SetPivotPoint(
        self, values: Sequence[str | float], unit: str | None = None
    ) -> None: ...
    def GetTemperature(self, unit: str | None = None) -> float: ...
    def SetTemperature(self, value: str | float, unit: str | None = None) -> None: ...
    def GetThermalBoundaryConditionType(self) -> str: ...
    def SetThermalBoundaryConditionType(self, value: str) -> None: ...
    def GetValidThermalBoundaryConditionTypeValues(self) -> list[str]: ...
    def GetTranslation(self, unit: str | None = None) -> list[float]: ...
    def SetTranslation(
        self, values: Sequence[str | float], unit: str | None = None
    ) -> None: ...
    def GetTriangleSize(self, unit: str | None = None) -> float: ...
    def SetTriangleSize(self, value: str | float, unit: str | None = None) -> None: ...
    def GetBoundaryMass(self, unit: str | None = None) -> float: ...
    def SetBoundaryMass(self, value: str | float, unit: str | None = None) -> None: ...
    def GetGravityCenter(self, unit: str | None = None) -> list[float]: ...
    def SetGravityCenter(
        self, values: Sequence[str | float], unit: str | None = None
    ) -> None: ...
    def GetMomentXDirection(self) -> list[float]: ...
    def SetMomentXDirection(self, values: list[str | float]) -> None: ...
    def GetMomentYDirection(self) -> list[float]: ...
    def SetMomentYDirection(self, values: list[str | float]) -> None: ...
    def GetMomentZDirection(self) -> list[float]: ...
    def SetMomentZDirection(self, values: list[str | float]) -> None: ...
    def GetPrincipalMomentOfInertia(self, unit: str | None = None) -> list[float]: ...
    def SetPrincipalMomentOfInertia(
        self, values: Sequence[str | float], unit: str | None = None
    ) -> None: ...
    def GetName(self) -> str: ...
    def SetName(self, value: str) -> None: ...
    def GetPeriodicReplication(self) -> bool: ...
    def SetPeriodicReplication(self, value: bool) -> None: ...
    def GetNumberOfReplications(self) -> int: ...
    def SetNumberOfReplications(self, value: str | int) -> None: ...
    def GetReplicateGeometry(self) -> bool: ...
    def SetReplicateGeometry(self, value: bool) -> None: ...
    def GetReplicateTime(self, unit: str | None = None) -> float: ...
    def SetReplicateTime(self, value: str | float, unit: str | None = None) -> None: ...
    def GetSphBoundaryType(self) -> str: ...
    def SetSphBoundaryType(self, value: str) -> None: ...
    def GetValidSphBoundaryTypeValues(self) -> list[str]: ...
    def GetSurfaceTensionContactAngle(self, unit: str | None = None) -> float: ...
    def SetSurfaceTensionContactAngle(
        self, value: str | float, unit: str | None = None
    ) -> None: ...
    def GetVolumeShearWorkRatio(self, unit: str | None = None) -> float: ...
    def SetVolumeShearWorkRatio(
        self, value: str | float, unit: str | None = None
    ) -> None: ...
    def GetWearModel(self) -> str: ...
    def SetWearModel(self, value: str) -> None: ...
    def GetValidWearModelValues(self) -> list[str]: ...
    def GetMaterial(self): ...
    def SetMaterial(self, value) -> None: ...
    def GetAvailableMaterials(self): ...
