from kraken20.plugins.api.ka_application import KAApplication
from pathlib import Path
from ansys.rocky.core._api_stubs.plugins10.plugins.api.api_element_item import ApiElementItem as ApiElementItem
from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_additional_features import RAAdditionalFeatures as RAAdditionalFeatures
from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_api import RockyApiError as RockyApiError
from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_matplotlib_window import RAMplWindow as RAMplWindow, UserWindowSubjectContainer as UserWindowSubjectContainer
from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_project import RAProject as RAProject
from ansys.rocky.core._api_stubs.rocky30.plugins.api.ra_study import RAStudy as RAStudy
from sci20.app.base_process import BaseProcess as BaseProcess
from typing import Union

class RockyApiApplication(KAApplication):
    def CreateProject(self) -> RAProject: ...
    def GetProject(self) -> RAProject: ...
    def OpenProject(self, filename: str) -> RAProject: ...
    def CloseProject(self, check_save_state: bool = ...) -> None: ...
    def SaveProject(self, filename: Union[str, None] = ...) -> None: ...
    def PlaybackMacroFile(self, filename: str) -> None: ...
    def PlaybackMacro(self, macro_name: str) -> None: ...
    def GetAdditionalFeatures(self) -> RAAdditionalFeatures: ...
    def GetVersion(self) -> str: ...
    def GetStudy(self, study_name: Union[str, None] = ...) -> RAStudy: ...
