from plugins10core.plugin import Plugin

class RockyModels:
    def GetWrapperClasses(self): ...
    def GetExtraAPIClasses(self): ...

class RockyApiPlugin(Plugin):
    def Install(self) -> None: ...
