from ansys.rocky.core._api_stubs.rocky30.plugins.api.motion.ra_motion_frame import RAMotionFrame as RAMotionFrame
from typing import Union

class _WithMovementMixin:
    def SetMotionFrame(self, motion_frame: Union['RAMotionFrame', str, None]) -> None: ...
    def GetMotionFrame(self) -> RAMotionFrame: ...
