from _typeshed import Incomplete
from collections.abc import Generator
from ansys.rocky.core._api_stubs.plugins10.plugins.api.api_element_item import ApiElementItem
from ansys.rocky.core._api_stubs.rocky30.plugins.api.motion.ra_motion_frame import RAMotionFrame as RAMotionFrame

class RABaseMotionFrame(ApiElementItem):
    def NewFrame(self) -> RAMotionFrame: ...
    def NewConeCrusherFrame(self): ...
    def IterMotionFrames(self) -> Generator[Incomplete, None, None]: ...
    def GetMotionFrame(self, frame_name): ...
    def RemoveFrame(self, motion_frame) -> None: ...
    def GetParentMotionFrame(self): ...
