from collections.abc import Sequence
from ansys.rocky.core._api_stubs.plugins10.plugins.api.api_element_item import ApiElementItem
from typing import List, Optional, Union

class RALinearTimeVariableForce(ApiElementItem):
    @classmethod
    def GetWrappedClass(self): ...
    @classmethod
    def GetClassName(self): ...
    def GetInitialForceValue(self, unit: Optional[str] = ...) -> List[float]: ...
    def SetInitialForceValue(self, values: Sequence[Union[str, float]], unit: Optional[str] = ...) -> None: ...
    def GetTimeCoefficients(self, unit: Optional[str] = ...) -> List[float]: ...
    def SetTimeCoefficients(self, values: Sequence[Union[str, float]], unit: Optional[str] = ...) -> None: ...
