from collections.abc import Sequence
from ansys.rocky.core._api_stubs.plugins10.plugins.api.api_element_item import ApiElementItem
from typing import List, Optional, Union

class RAPrescribedMoment(ApiElementItem):
    @classmethod
    def GetWrappedClass(self): ...
    @classmethod
    def GetClassName(self): ...
    def GetMomentValue(self, unit: Optional[str] = ...) -> List[float]: ...
    def SetMomentValue(self, values: Sequence[Union[str, float]], unit: Optional[str] = ...) -> None: ...
