from collections.abc import Sequence
from ansys.rocky.core._api_stubs.plugins10.plugins.api.api_element_item import ApiElementItem
from typing import List, Optional, Union

class RARotation(ApiElementItem):
    @classmethod
    def GetWrappedClass(self): ...
    @classmethod
    def GetClassName(self): ...
    def GetAngularAcceleration(self, unit: Optional[str] = ...) -> List[float]: ...
    def SetAngularAcceleration(self, values: Sequence[Union[str, float]], unit: Optional[str] = ...) -> None: ...
    def GetInitialAngularVelocity(self, unit: Optional[str] = ...) -> List[float]: ...
    def SetInitialAngularVelocity(self, values: Sequence[Union[str, float]], unit: Optional[str] = ...) -> None: ...
