from ansys.rocky.core._api_stubs.plugins10.plugins.api.api_element_item import ApiElementItem
from typing import List, Optional, Union

class RASpringDashpotForce(ApiElementItem):
    @classmethod
    def GetWrappedClass(self): ...
    @classmethod
    def GetClassName(self): ...
    def GetDashpotCoefficient(self, unit: Optional[str] = ...) -> float: ...
    def SetDashpotCoefficient(self, value: Union[str, float], unit: Optional[str] = ...) -> None: ...
    def GetDirection(self) -> str: ...
    def SetDirection(self, value: str) -> None: ...
    def GetValidDirectionValues(self) -> List[str]: ...
    def GetSpringCoefficient(self, unit: Optional[str] = ...) -> float: ...
    def SetSpringCoefficient(self, value: Union[str, float], unit: Optional[str] = ...) -> None: ...
